-- Allow NULL values for contribution_id to support bulk imports
ALTER TABLE dictionary_entries ALTER COLUMN contribution_id DROP NOT NULL;
ALTER TABLE dictionary_entries ALTER COLUMN contributor_id DROP NOT NULL;

-- Insert new Goji dictionary entries batch 3
INSERT INTO dictionary_entries (
  goji_word, 
  english_translation, 
  hausa_translation, 
  example_sentence, 
  cultural_context, 
  part_of_speech,
  difficulty_level,
  contribution_id,
  contributor_id,
  approved_at
) VALUES 
-- L entries
('là', 'child, son', 'ɗa', NULL, 'Plural: shíbó, cíbó', 'n', 'beginner', NULL, NULL, now()),
('láɣát (shìk)', 'skin (body)', 'fatar jiki', NULL, NULL, 'n', 'beginner', NULL, NULL, now()),
('là gèɣè', 'bride (girl not married)', NULL, NULL, NULL, 'n', 'intermediate', NULL, NULL, now()),
('láját', 'outfit of hunter', 'rigar mafarauci', NULL, NULL, 'n', 'intermediate', NULL, NULL, now()),
('là ɗúndì', 'small bottle gourd', 'buta', NULL, NULL, 'n', 'intermediate', NULL, NULL, now()),
('làkà', 'orphan', 'maraya', NULL, NULL, 'n', 'intermediate', NULL, NULL, now()),
('là gàráyà', 'musical bow', 'izga', NULL, NULL, 'n', 'intermediate', NULL, NULL, now()),
('làllò', 'ruminate', 'ci (saniya)', NULL, NULL, 'v', 'intermediate', NULL, NULL, now()),
('là mínná', 'servant', 'bara, barabya', NULL, 'Literally: boy (of) house', 'n', 'intermediate', NULL, NULL, now()),
('làmbú', 'garden', 'gadina, lamu', NULL, NULL, 'n', 'beginner', NULL, NULL, now()),
('lànnà', 'clothes', 'tufafi', NULL, NULL, 'n', 'beginner', NULL, NULL, now()),
('là shìrìp', 'daughter', 'ya mace, ɗiya', NULL, 'Plural: cíbó shìrìp', 'n', 'beginner', NULL, NULL, now()),
('lèeláw', 'cotton', 'auduga', NULL, NULL, 'n', 'intermediate', NULL, NULL, now()),
('là shúrùk', 'seasonal river', 'kogi', NULL, NULL, 'n', 'intermediate', NULL, NULL, now()),
('léɣá', 'desire', 'shaʔawa', NULL, NULL, 'n', 'intermediate', NULL, NULL, now()),
('là shùɣì', 'boy, son', 'ɗa', NULL, 'Plural: cíbó shùɣì', 'n', 'beginner', NULL, NULL, now()),
('lèwɔ̀', 'want, like, love', 'so', NULL, NULL, 'v', 'beginner', NULL, NULL, now()),
('là tálàŋ', 'pot for cooking soup', 'tukunya', NULL, NULL, 'n', 'intermediate', NULL, NULL, now()),
('lí', 'put', 'sa', NULL, NULL, 'v', 'beginner', NULL, NULL, now()),
('là témmè', 'calabash for drinking beer', 'duma', NULL, NULL, 'n', 'intermediate', NULL, NULL, now()),
('lìlámdè', 'butterfly', 'malam-buɗa-mana-littafi', NULL, NULL, 'n', 'beginner', NULL, NULL, now()),
('láalá', 'spider', 'gizo-gizo', NULL, 'mínná láalá = cobweb', 'n', 'beginner', NULL, NULL, now()),
('lɔ̀ɔ', 'meat', 'nama', NULL, 'lɔ̀(ɔ) tà shwè = bush meat (naman daji)', 'n', 'beginner', NULL, NULL, now()),
('láayá', 'charm', 'laya', NULL, NULL, 'n', 'intermediate', NULL, NULL, now()),
('lúrú', 'bag', 'jaka', NULL, NULL, 'n', 'beginner', NULL, NULL, now()),
('láɗú', 'grey sesame', 'riɗi', NULL, NULL, 'n', 'intermediate', NULL, NULL, now()),
('lùgnì', 'shade', 'inuwa', NULL, NULL, 'n', 'beginner', NULL, NULL, now()),
('làɗì', 'north', 'arewa', NULL, NULL, 'n', 'beginner', NULL, NULL, now()),
('lùmmò', 'flour', 'gari', NULL, NULL, 'n', 'beginner', NULL, NULL, now()),
('láɣát', 'leather, skin (animal)', 'fata (dabba)', NULL, NULL, 'n', 'beginner', NULL, NULL, now()),
('lùmmò ɓùk', 'fine sand', 'rairayi', NULL, NULL, 'n', 'intermediate', NULL, NULL, now()),

-- M entries
('màlàc', 'rainbow', 'bakan gizo', NULL, NULL, 'n', 'beginner', NULL, NULL, now()),
('mínná', 'house', 'gida', NULL, NULL, 'n', 'beginner', NULL, NULL, now()),
('màlàc dòo', 'rainbow', 'bakan gizo', NULL, 'See: màlàc', 'n', 'beginner', NULL, NULL, now()),
('mínná gùp', 'palace', 'gidan sarki', NULL, NULL, 'n', 'intermediate', NULL, NULL, now()),
('màlɣò', 'lightning', 'walƙiya', NULL, NULL, 'n', 'beginner', NULL, NULL, now()),
('mínná kə̀nímmà', 'oracle', NULL, NULL, NULL, 'n', 'advanced', NULL, NULL, now()),
('màmmà', 'ant-hill', 'jiɓa, suri, shuri', NULL, NULL, 'n', 'intermediate', NULL, NULL, now()),
('mòɗɗò', 'millet', 'gero', NULL, NULL, 'n', 'beginner', NULL, NULL, now()),
('màŋlàŋ', 'skull', 'ƙwaƙwalwa, kwanya', NULL, NULL, 'n', 'intermediate', NULL, NULL, now()),
('mòllò', 'brother', 'ƙane', NULL, NULL, 'n', 'beginner', NULL, NULL, now()),
('mánná', 'husband', 'miji', NULL, NULL, 'n', 'beginner', NULL, NULL, now()),
('mòllà', 'sister', NULL, NULL, 'mòllà nɔ̀nnɔ́ = mother''s sister', 'n', 'beginner', NULL, NULL, now()),
('mə̀n', 'beer', 'giya', NULL, NULL, 'n', 'intermediate', NULL, NULL, now()),
('mòlón', 'relative', 'dangi', NULL, NULL, 'n', 'beginner', NULL, NULL, now()),
('mə̀n ɗíyè', 'beer pot', 'tulun giya', NULL, NULL, 'n', 'intermediate', NULL, NULL, now()),
('mɔ̀n tùɣànò', 'drunk', 'bugagge', NULL, 'Literally: beer killed me', 'n, adj', 'intermediate', NULL, NULL, now()),
('mè àn', 'many', 'da yawa', NULL, NULL, 'adv', 'beginner', NULL, NULL, now()),
('méemé', 'wasp', 'zanzaro', NULL, NULL, 'n', 'beginner', NULL, NULL, now()),
('Mèerò', 'make, braid rope', NULL, NULL, NULL, 'v', 'intermediate', NULL, NULL, now()),
('mɔ̀r', 'oil', 'mai', NULL, NULL, 'n', 'beginner', NULL, NULL, now()),
('mèrà', 'travel', 'tafiya', NULL, NULL, 'n', 'beginner', NULL, NULL, now()),
('mɔ̀r tàngà', 'butter', 'man shanu', NULL, NULL, 'n', 'intermediate', NULL, NULL, now()),
('mìɗò', 'stirring stick', 'muciya', NULL, NULL, 'n', 'intermediate', NULL, NULL, now()),
('móotò', 'car', 'mota', NULL, NULL, 'n', 'beginner', NULL, NULL, now()),
('mìigù', 'owl', 'mugiya', NULL, NULL, 'n', 'beginner', NULL, NULL, now()),
('múlkì', 'chieftancy', 'sarauta', NULL, NULL, 'n', 'advanced', NULL, NULL, now()),
('mìllán kpòolɔ́', 'last year', 'bara', NULL, NULL, 'adv', 'intermediate', NULL, NULL, now()),
('mùrɔ̀', 'die', 'mutu', NULL, NULL, 'v', 'beginner', NULL, NULL, now()),
('mìmé', 'people', 'mutane', NULL, NULL, 'n', 'beginner', NULL, NULL, now()),
('mùshì', 'jealousy', 'kishi', NULL, NULL, 'n', 'intermediate', NULL, NULL, now()),

-- N entries
('nàa', 'elephant', 'giwa', NULL, NULL, 'n', 'beginner', NULL, NULL, now()),
('nìŋò', 'person, man', 'mutum', NULL, 'Plural: mìmé', 'n', 'beginner', NULL, NULL, now()),
('nàa prt', 'particle used to form numerals', NULL, NULL, NULL, 'prt', 'intermediate', NULL, NULL, now()),
('nìŋòn dìn', 'black man', NULL, NULL, NULL, 'n', 'intermediate', NULL, NULL, now()),
('nàa tààt', 'thirty', 'talatin', NULL, NULL, 'num', 'intermediate', NULL, NULL, now()),
('nìŋòn gàràl', 'white man', 'bature', NULL, NULL, 'n', 'intermediate', NULL, NULL, now()),
('nàa fúwàt', 'fifty', 'hamsin', NULL, NULL, 'num', 'intermediate', NULL, NULL, now()),
('nìyò', 'mature, become ripe', 'nuna', NULL, NULL, 'v', 'intermediate', NULL, NULL, now()),
('náanì', 'thunder', 'hadari', NULL, NULL, 'n', 'beginner', NULL, NULL, now()),
('nɔ̀nnɔ́', 'mother', 'uwa', NULL, NULL, 'n', 'beginner', NULL, NULL, now()),
('nèsshò', 'rest', 'huta', NULL, NULL, 'v', 'beginner', NULL, NULL, now()),
('ŋɔ̀rì', 'rainbird', NULL, NULL, NULL, 'n', 'intermediate', NULL, NULL, now()),
('nèy', 'fight', 'faɗa', NULL, NULL, 'n', 'beginner', NULL, NULL, now()),
('nùrò', 'heal', 'warke, warkar da', NULL, NULL, 'v', 'intermediate', NULL, NULL, now()),
('nìmmì', 'near', 'kusa', NULL, 'à nìmmìm = not near (ba kusa ba)', 'adv', 'beginner', NULL, NULL, now()),

-- O entries
('ɔ́ɣrɔ́', 'bottle', 'kwlaba', NULL, NULL, 'n', 'beginner', NULL, NULL, now()),
('ɔ̀ppɔ̀ dùwò', 'funeral', 'jana''iza', NULL, 'Literally: digging grave', 'n', 'intermediate', NULL, NULL, now()),
('ɔ̀ppɔ̀', 'dig', 'haƙa', NULL, NULL, 'v', 'beginner', NULL, NULL, now()),
('òshò', 'swell', 'kumbura', NULL, NULL, 'v', 'intermediate', NULL, NULL, now()),

-- P entries
('pámmò', 'ordeal', NULL, NULL, NULL, 'n', 'advanced', NULL, NULL, now()),
('péewé', 'outside', 'waje', NULL, NULL, 'adv', 'beginner', NULL, NULL, now()),
('pàrɔ̀', 'herd (animals)', NULL, NULL, NULL, 'v', 'intermediate', NULL, NULL, now()),
('pèrèt', 'mosquito', 'sauro', NULL, NULL, 'n', 'beginner', NULL, NULL, now()),
('pàttò', 'give birth', 'haifa', NULL, NULL, 'v', 'beginner', NULL, NULL, now()),
('pèrɔ̀', 'go out', 'fita', NULL, NULL, 'v', 'beginner', NULL, NULL, now()),
('pə̀ək', 'lungs', 'huhu', NULL, NULL, 'n', 'intermediate', NULL, NULL, now()),
('pìdìɗòw', 'eight', 'takwas', NULL, NULL, 'num', 'beginner', NULL, NULL, now()),
('pə̀əmún', 'female, wife', 'mace', NULL, 'Plural: shìrìp', 'n', 'beginner', NULL, NULL, now()),
('pìl', 'hook', 'ƙugiya', NULL, NULL, 'n', 'intermediate', NULL, NULL, now()),
('pə̀llɔ̀w', 'two', 'biyu', NULL, NULL, 'num', 'beginner', NULL, NULL, now()),
('pírá', 'sore, wound, disease', 'rauni', NULL, NULL, 'n', 'intermediate', NULL, NULL, now()),
('pè', 'white', 'fari', NULL, NULL, 'adj', 'beginner', NULL, NULL, now()),
('pìrìt', 'wind', 'iska', NULL, NULL, 'n', 'beginner', NULL, NULL, now()),
('péèn', 'seed', NULL, NULL, NULL, 'n', 'beginner', NULL, NULL, now()),
('pìrìt dòo', 'storm', 'ruwa da iska', NULL, NULL, 'n', 'intermediate', NULL, NULL, now()),
('péeròw', 'four', 'huɗu', NULL, NULL, 'num', 'beginner', NULL, NULL, now()),
('pìrù', 'come out', 'fito', NULL, NULL, 'v', 'beginner', NULL, NULL, now()),

-- R entries
('ràagúmì', 'camel', 'raƙumi', NULL, NULL, 'n', 'beginner', NULL, NULL, now()),
('réy', 'life', 'rai', NULL, NULL, 'n', 'beginner', NULL, NULL, now()),
('rèeké', 'sugar cane', 'kara', NULL, NULL, 'n', 'beginner', NULL, NULL, now()),
('ríibà', 'profit', 'riba', NULL, NULL, 'n', 'intermediate', NULL, NULL, now()),
('rêw', 'python', 'mesa', NULL, 'See: kúrét, shàmmàm', 'n', 'intermediate', NULL, NULL, now()),
('ríijà', 'well', 'rijiya', NULL, NULL, 'n', 'beginner', NULL, NULL, now()),
('rə́wák', 'baboon', 'gwaggon biri', NULL, NULL, 'n', 'intermediate', NULL, NULL, now()),
('ríwít', 'fire-place', 'wurin wuta', NULL, NULL, 'n', 'intermediate', NULL, NULL, now()),
('rè', 'enter', 'shiga', NULL, NULL, 'v', 'beginner', NULL, NULL, now()),
('ròmìsh', 'twin', 'ɗan tagwai', NULL, NULL, 'n', 'intermediate', NULL, NULL, now());