-- Insert comprehensive English-to-Goji dictionary entries (batch 7 - A-Z)
INSERT INTO dictionary_entries (goji_word, english_translation, hausa_translation, part_of_speech, difficulty_level) VALUES
-- A entries
('dàŋ', 'above', '', 'preposition', 'beginner'),
('bànà', 'antelope', '', 'noun', 'intermediate'),
('gùlmà', 'accusation', '', 'noun', 'intermediate'),
('gbɔ̀nnà', 'across', '', 'preposition', 'intermediate'),
('ɣèerè', 'age-mate', '', 'noun', 'intermediate'),
('fɔ̀ gùn', 'anus', '', 'noun', 'beginner'),
('gùn', 'anus', '', 'noun', 'beginner'),
('jènè', 'aridity', '', 'noun', 'advanced'),
('jìijí', 'ancestor', '', 'noun', 'intermediate'),
('kírá', 'arm', '', 'noun', 'beginner'),
('gbárlàm', 'anklet', '', 'noun', 'intermediate'),
('tà ɓə̀ək', 'armpit', '', 'noun', 'beginner'),
('dòlòní', 'ant', '', 'noun', 'beginner'),
('fɔ̀yɔ́', 'ant', '', 'noun', 'beginner'),
('shíwó', 'ant', '', 'noun', 'beginner'),
('twɔ̀ŋé', 'ant', '', 'noun', 'beginner'),
('áyúkh', 'ant', '', 'noun', 'beginner'),
('fíìk', 'arrow', '', 'noun', 'intermediate'),
('vùrɔ̀', 'ashes', '', 'noun', 'beginner'),
('tà', 'at', '', 'preposition', 'beginner'),
('gbàamé', 'axe', '', 'noun', 'intermediate'),

-- B entries
('rə́wák', 'baboon', '', 'noun', 'intermediate'),
('ʔàn kùwà', 'blacksmith', '', 'noun', 'intermediate'),
('bì', 'back', '', 'noun', 'beginner'),
('gódó', 'blanket', '', 'noun', 'beginner'),
('lúrú', 'bag', '', 'noun', 'beginner'),
('fùgùm', 'blind', '', 'adjective', 'intermediate'),
('dùurò', 'bambara nut', '', 'noun', 'intermediate'),
('shìk', 'body', '', 'noun', 'beginner'),
('ɓánnì', 'baobab', '', 'noun', 'intermediate'),
('ɗùmmò', 'boil', '', 'verb', 'beginner'),
('gáŋà', 'basket', '', 'noun', 'beginner'),
('jàrà', 'basket', '', 'noun', 'beginner'),
('jùŋroŋ', 'basket', '', 'noun', 'beginner'),
('jə̀ə', 'bean(s)', '', 'noun', 'beginner'),
('kə̀rə̀k', 'border', '', 'noun', 'intermediate'),
('ɔ́ɣrɔ́', 'bottle', '', 'noun', 'beginner'),
('shɔ́k fɔ̀k', 'beard', '', 'noun', 'beginner'),
('kírá bìró', 'branch', '', 'noun', 'intermediate'),
('ɓìrò', 'beat', '', 'verb', 'beginner'),
('jìrà', 'bed', '', 'noun', 'beginner'),
('shégní', 'bee', '', 'noun', 'beginner'),
('mə̀n', 'beer', '', 'noun', 'intermediate'),
('shàŋà', 'bridegroom', '', 'noun', 'intermediate'),
('pàttò', 'beget', '', 'verb', 'intermediate'),
('tèrèt', 'broom', '', 'noun', 'beginner'),
('káráráwá', 'bell', '', 'noun', 'intermediate'),
('mòllò', 'brother', '', 'noun', 'beginner'),
('fùgrò', 'bellows', '', 'noun', 'intermediate'),
('bùkwátì', 'bucket', '', 'noun', 'beginner'),
('gɔ̀ŋɔ̀', 'belly', '', 'noun', 'beginner'),
('ɗìgù', 'build', '', 'verb', 'intermediate'),
('shékì', 'between', '', 'preposition', 'intermediate'),
('tàŋgà', 'bull', '', 'noun', 'intermediate'),
('gbé', 'big', '', 'adjective', 'beginner'),
('ɗáwán', 'bundle', '', 'verb', 'intermediate'),
('ʔàɗéewè', 'bird', '', 'noun', 'beginner'),
('shwè', 'bush', '', 'noun', 'intermediate'),
('yèrò', 'bite', '', 'verb', 'beginner'),
('ʔàn páawà', 'butcher', '', 'noun', 'intermediate'),
('dìŋ2', 'black', '', 'adjective', 'beginner'),
('mɔ̀r tàngà', 'butter', '', 'noun', 'intermediate'),
('lìlámdè', 'butterfly', '', 'noun', 'intermediate'),

-- C entries
('gùráŋ', 'calabash', '', 'noun', 'intermediate'),
('shén', 'cleverness', '', 'noun', 'advanced'),
('témmè1', 'cleverness', '', 'noun', 'advanced'),
('ʔàmmò', 'climb up', '', 'verb', 'intermediate'),
('yɔ̀', 'call', '', 'verb', 'beginner'),
('lànnà', 'clothes', '', 'noun', 'beginner'),
('ràagúmì', 'camel', '', 'noun', 'intermediate'),
('shùngù', 'cloud', '', 'noun', 'beginner'),
('rèeké', 'cane (sugar)', '', 'noun', 'intermediate'),
('vìɣè', 'cobra', '', 'noun', 'intermediate'),
('móotò', 'car', '', 'noun', 'beginner'),
('gòkh', 'cock', '', 'noun', 'beginner'),
('gbàaɣò', 'carve', '', 'verb', 'intermediate'),
('gwàaja', 'cocoyam', '', 'noun', 'intermediate'),
('tà kɔ̀n', 'case', '', 'noun', 'intermediate'),
('pìrù', 'come out', '', 'verb', 'beginner'),
('jéné', 'caterpillar', '', 'noun', 'intermediate'),
('ɗìŋò', 'cook', '', 'verb', 'beginner'),
('vùlùk', 'cave', '', 'noun', 'intermediate'),
('ɗùulò', 'cool', '', 'verb', 'beginner'),
('jùk2', 'chair', '', 'noun', 'beginner'),
('ìshì shwè', 'cornstalk', '', 'noun', 'intermediate'),
('dìmlìm', 'charcoal', '', 'noun', 'intermediate'),
('kúmá', 'corpse', '', 'noun', 'intermediate'),
('láayá', 'charm', '', 'noun', 'intermediate'),
('lèeláw', 'cotton', '', 'noun', 'intermediate'),
('shùuɣò', 'cheat', '', 'verb', 'intermediate'),
('shìm', 'cough', '', 'noun', 'beginner'),
('jáɣlùm', 'cheek', '', 'noun', 'beginner'),
('ɓán fɔ̀k', 'courage', '', 'noun', 'advanced'),
('gbìilì', 'chest', '', 'noun', 'beginner'),
('khèwnè', 'cow', '', 'noun', 'beginner'),
('féè', 'chicken', '', 'noun', 'beginner'),
('kènè ɗìyò', 'cowrie', '', 'noun', 'intermediate'),
('gùp', 'chief', '', 'noun', 'intermediate'),
('khùrùwò', 'cowry', '', 'noun', 'intermediate'),
('múlkì', 'chieftaincy', '', 'noun', 'advanced'),
('jènyè', 'crab', '', 'noun', 'intermediate'),
('là', 'child', '', 'noun', 'beginner'),
('jwàlé', 'cricket', '', 'noun', 'intermediate'),
('vèe', 'chin', '', 'noun', 'beginner'),
('kèrèm', 'crocodile', '', 'noun', 'intermediate'),
('kàr kúwò', 'circumcision', '', 'noun', 'advanced'),
('gàakh', 'crow', '', 'noun', 'intermediate'),
('kɔ̀ɗɔ̀', 'claw', '', 'noun', 'intermediate'),
('kùwák', 'curse', '', 'noun', 'intermediate'),
('ɗɔ̀ɣbɔ́', 'clay', '', 'noun', 'intermediate'),
('jáwít', 'cutlery', '', 'noun', 'intermediate'),
('tèmmò', 'clean', '', 'verb', 'beginner'),

-- D entries
('shɔ̀r', 'dance', '', 'noun', 'beginner'),
('ʔàn shɔ̀r', 'dancer', '', 'noun', 'intermediate'),
('ɓày', 'dog', '', 'noun', 'beginner'),
('gɔ̀ŋlàŋ', 'date', '', 'noun', 'intermediate'),
('gìrbì', 'donkey', '', 'noun', 'beginner'),
('là shìrìp', 'daughter', '', 'noun', 'beginner'),
('dáŋ', 'door', '', 'noun', 'beginner'),
('gbàrìm', 'daughter-in-law', '', 'noun', 'intermediate'),
('fɔ̀ dáŋ', 'doorway', '', 'noun', 'intermediate'),
('kíríyípɔ́', 'dawn', '', 'noun', 'intermediate'),
('kùmùm', 'doubt', '', 'noun', 'intermediate'),
('kà dàràŋ', 'daylight', '', 'noun', 'intermediate'),
('shúná', 'dream', '', 'noun', 'beginner'),
('kúwó', 'debt', '', 'noun', 'intermediate'),
('shɔ̀', 'drink', '', 'verb', 'beginner'),
('vìyò', 'demon', '', 'noun', 'intermediate'),
('gàŋgàŋ', 'drum', '', 'noun', 'intermediate'),
('pírá', 'disease', '', 'noun', 'intermediate'),
('ʔàn gàŋgàŋ', 'drummer', '', 'noun', 'intermediate'),
('léɣá', 'desire', '', 'noun', 'advanced'),
('mɔ̀n tùɣànò', 'drunk', '', 'adjective', 'intermediate'),
('shwíyə̀k', 'dew', '', 'noun', 'intermediate'),
('íshàn', 'dry', '', 'adjective', 'beginner'),
('sháppàn', 'diarrhea', '', 'noun', 'intermediate'),
('ʔìshò', 'dry up', '', 'verb', 'intermediate'),
('mùrɔ̀', 'die', '', 'verb', 'beginner'),
('ʔàgwàgwá', 'duck', '', 'noun', 'intermediate'),
('ʔɔ́ppɔ̀', 'dig', '', 'verb', 'beginner'),
('kúnná', 'dysentery', '', 'noun', 'intermediate'),
('ɓwàarò ɗìyò', 'divorce', '', 'noun', 'advanced'),

-- E entries
('kúmó', 'ear', '', 'noun', 'beginner'),
('ʔàn gèy', 'enemy', '', 'noun', 'intermediate'),
('ɓɔ̀ɔlì', 'east', '', 'noun', 'intermediate'),
('rè', 'enter', '', 'verb', 'beginner'),
('shù', 'eat', '', 'verb', 'beginner'),
('fɔ̀ɔrà kúnò', 'escape', '', 'noun', 'intermediate'),
('ʔàɗɗɔ̀', 'eat', '', 'verb', 'beginner'),
('shìilà ɓàalà', 'escarpment', '', 'noun', 'advanced'),
('pìdìɗòw', 'eight', '', 'number', 'beginner'),
('gùŋgúl', 'elbow', '', 'noun', 'beginner'),
('shànɣò', 'exchange', '', 'verb', 'intermediate'),
('nɔ̀nnɔ́-nɔ̀nnɔ́', 'elder sisters of mother', '', 'noun', 'advanced'),
('ʔàɗò', 'eye', '', 'noun', 'beginner'),
('jùk1', 'elephant', '', 'noun', 'intermediate'),
('nàa', 'elephant', '', 'noun', 'intermediate'),

-- F entries
('shùkkàn kírá', 'fist', '', 'noun', 'intermediate'),
('tà mínná(nò)', 'family', '', 'noun', 'intermediate'),
('fúwàt', 'five', '', 'number', 'beginner'),
('tálí', 'far', '', 'adverb', 'intermediate'),
('ɓìr(ì) shàw', 'flail', '', 'noun', 'advanced'),
('dɔ̀ŋ', 'farm', '', 'noun', 'intermediate'),
('shìɗə̀r', 'fat', '', 'noun', 'beginner'),
('gàarì', 'flea', '', 'noun', 'intermediate'),
('tàará', 'father', '', 'noun', 'beginner'),
('lɔ̀ɔ', 'flesh', '', 'noun', 'beginner'),
('shéwó', 'fear', '', 'noun', 'intermediate'),
('lùmmò', 'flour', '', 'noun', 'beginner'),
('shɔ̀kh', 'feather', '', 'noun', 'intermediate'),
('bìlìr', 'flower', '', 'noun', 'beginner'),
('pə̀əmún', 'female', '', 'noun', 'beginner'),
('dùyó', 'fly', '', 'noun', 'beginner'),
('dàngà', 'fence', '', 'noun', 'intermediate'),
('fùumò', 'fence', '', 'noun', 'intermediate'),
('fúvùl', 'foam', '', 'noun', 'intermediate'),
('dàbáŋ', 'festival', '', 'noun', 'intermediate'),
('gwàŋ', 'food', '', 'noun', 'beginner'),
('kə̀nímmà', 'fetish', '', 'noun', 'advanced'),
('shò', 'foot', '', 'noun', 'beginner'),
('tɔ̀ɗókù', 'fever', '', 'noun', 'intermediate'),
('bì shò', 'footprint', '', 'noun', 'intermediate'),
('fɔ̀ɔrɔ̀', 'forehead', '', 'noun', 'beginner'),
('nèy', 'fight', '', 'noun', 'intermediate'),
('dìl bìró', 'forest', '', 'noun', 'intermediate'),
('kùwà', 'forge', '', 'verb', 'advanced'),
('jɔ̀d', 'filter', '', 'noun', 'intermediate'),
('péeròw', 'four', '', 'number', 'beginner'),
('kɔ̀shɔ̀', 'filter', '', 'verb', 'intermediate'),
('ʔàntórò', 'francolin', '', 'noun', 'advanced'),
('fɔ̀ kírá', 'finger', '', 'noun', 'beginner'),
('jèrè', 'friend', '', 'noun', 'beginner'),
('dèet', 'fire', '', 'noun', 'beginner'),
('dànyùkh', 'frog', '', 'noun', 'intermediate'),
('ríwít', 'fire-place', '', 'noun', 'intermediate'),
('shùurò', 'fry', '', 'verb', 'beginner'),
('shíiwé', 'firewood', '', 'noun', 'intermediate'),
('ɔ̀ppɔ̀ dùwò', 'funeral', '', 'noun', 'intermediate'),
('shìrìm', 'fish', '', 'noun', 'beginner'),

-- G entries
('làmbú', 'garden', '', 'noun', 'intermediate'),
('gàaɣá', 'grandmother', '', 'noun', 'beginner'),
('áɗáy', 'gazelle', '', 'noun', 'intermediate'),
('gɔ̀lɔ̀m', 'grasshopper', '', 'noun', 'intermediate'),
('ʔàntúgó', 'gecko', '', 'noun', 'intermediate'),
('dùwò', 'grave', '', 'noun', 'intermediate'),
('dùwò', 'ghost', '', 'noun', 'intermediate'),
('ʔìshɔ̀', 'grind', '', 'verb', 'beginner'),
('pèrɔ̀', 'go out', '', 'verb', 'beginner'),
('vìn', 'grinding stone', '', 'noun', 'intermediate'),
('vàré', 'goat', '', 'noun', 'beginner'),
('tà ɓùk', 'ground', '', 'noun', 'beginner'),
('kù ɓùk', 'ground', '', 'noun', 'beginner'),
('gbáŋ', 'goodness', '', 'noun', 'advanced'),
('dùwàaɣnò', 'groundnut', '', 'noun', 'intermediate'),
('áeshàw', 'grain', '', 'noun', 'intermediate'),
('kháa', 'gruel', '', 'noun', 'intermediate'),
('káŋ', 'granary', '', 'noun', 'intermediate'),
('bìnnò', 'guest', '', 'noun', 'intermediate'),
('jìijí', 'grandfather', '', 'noun', 'beginner'),
('túmmò', 'guinea-fowl', '', 'noun', 'intermediate'),
('bìndìgà', 'gun', '', 'noun', 'intermediate'),

-- H entries
('ʔàdéelè', 'hail', '', 'noun', 'intermediate'),
('fɔ̀tè', 'here', '', 'adverb', 'beginner'),
('shɔ́k', 'hair', '', 'noun', 'beginner'),
('shégrí', 'hiccough', '', 'noun', 'intermediate'),
('shìilà', 'hill', '', 'noun', 'intermediate'),
('dúmmò', 'hoe', '', 'noun', 'intermediate'),
('shùrmì', 'hare', '', 'noun', 'intermediate'),
('káyò', 'hoe', '', 'verb', 'intermediate'),
('káshò', 'harvest', '', 'noun', 'intermediate'),
('gbáaɣò', 'hollow out', '', 'verb', 'intermediate'),
('kàshò', 'harvest', '', 'verb', 'intermediate'),
('pìl', 'hook', '', 'noun', 'intermediate'),
('gètè', 'hawk', '', 'noun', 'intermediate'),
('kpàa', 'horn', '', 'noun', 'intermediate'),
('khù', 'head', '', 'noun', 'beginner'),
('ʔàdúnúnò', 'horn', '', 'noun', 'intermediate'),
('gbɔ́shì', 'headpad', '', 'noun', 'intermediate'),
('gùrùŋ', 'horse', '', 'noun', 'intermediate'),
('nùrò', 'heal', '', 'verb', 'intermediate'),
('mínná', 'house', '', 'noun', 'beginner'),
('ʔàn wùrìn', 'healer', '', 'noun', 'intermediate'),
('shìk', 'hundred', '', 'number', 'intermediate'),
('fɔ̀ shə̀ərì', 'heart', '', 'noun', 'beginner'),
('kúyám', 'hunger', '', 'noun', 'beginner'),
('kù dàŋ', 'heaven', '', 'noun', 'advanced'),
('ʔàkùmóm', 'hedgehog', '', 'noun', 'intermediate'),
('ʔàn tà shwè', 'hunter', '', 'noun', 'intermediate'),
('bìirìm', 'heel', '', 'noun', 'beginner'),
('mánná', 'husband', '', 'noun', 'beginner'),
('pàrɔ̀', 'herd', '', 'verb', 'intermediate'),
('gùmè', 'hut', '', 'noun', 'intermediate'),
('də̀ɓɓà', 'hyena', '', 'noun', 'intermediate'),

-- I, J entries
('tà', 'in', '', 'preposition', 'beginner'),
('jáŋ', 'jaw', '', 'noun', 'beginner'),
('kɔ̀n', 'judge', '', 'noun', 'intermediate'),
('mùshì', 'jealousy', '', 'noun', 'advanced'),
('jùwò', 'jump', '', 'verb', 'beginner'),

-- K entries
('tùɣò', 'kill', '', 'verb', 'intermediate'),
('vùrùm', 'knee', '', 'noun', 'beginner'),

-- L entries
('gùngù', 'lame', '', 'adjective', 'intermediate'),
('réy', 'life', '', 'noun', 'advanced'),
('fɔ̀k', 'language', '', 'noun', 'intermediate'),
('màlɣò', 'lightning', '', 'noun', 'intermediate'),
('mìllán kpòolɔ́', 'last year', '', 'adverb', 'intermediate'),
('tà mínná(mù)', 'lineage', '', 'noun', 'advanced'),
('dìŋ1', 'laterite', '', 'noun', 'advanced'),
('kàmmà', 'lion', '', 'noun', 'intermediate'),
('shúrɔ́', 'laugh', '', 'noun', 'beginner'),
('lèwɔ̀', 'like', '', 'verb', 'beginner'),
('kùulè', 'lazy', '', 'adjective', 'intermediate'),
('fɔ̀ lùwàk', 'liver', '', 'noun', 'intermediate'),
('kèlà', 'leaf', '', 'noun', 'beginner'),
('ʔàntúgó', 'lizard', '', 'noun', 'intermediate'),
('ʔàlàw', 'leaf', '', 'noun', 'beginner'),
('an límmò láɣát', 'leatherworker', '', 'noun', 'advanced'),
('shárí', 'load', '', 'noun', 'intermediate'),
('jìyaw', 'left', '', 'adverb', 'beginner'),
('jɔ́rrɔ́', 'locust', '', 'noun', 'intermediate'),
('shò', 'leg', '', 'noun', 'beginner'),
('jàmmó', 'loom', '', 'noun', 'intermediate'),
('kùwò', 'lend', '', 'verb', 'intermediate'),
('shíɣá', 'loss', '', 'noun', 'intermediate'),
('jàŋàní', 'leopard', '', 'noun', 'intermediate'),
('shábá', 'lie', '', 'noun', 'intermediate'),
('pə̀ək', 'lungs', '', 'noun', 'intermediate'),

-- M entries
('kɔ̀ɔmɔ̀', 'maize', '', 'noun', 'beginner'),
('shíyá', 'menstruation', '', 'noun', 'intermediate'),
('dòo wùrì', 'milk', '', 'noun', 'beginner'),
('fìléríyà', 'malaria', '', 'noun', 'intermediate'),
('mòɗɗò', 'millet', '', 'noun', 'intermediate'),
('shùjì', 'male', '', 'noun', 'beginner'),
('gə̀rùm', 'molar', '', 'noun', 'intermediate'),
('shújí', 'male', '', 'noun', 'beginner'),
('kə́nə́', 'money', '', 'noun', 'beginner'),
('ʔàkúlà', 'mantis', '', 'noun', 'intermediate'),
('shìlím', 'mongoose', '', 'noun', 'intermediate'),
('mè ʔàn', 'many', '', 'adverb', 'intermediate'),
('jìró', 'monkey', '', 'noun', 'intermediate'),
('gùrùŋ', 'mare', '', 'noun', 'intermediate'),
('téré', 'moon', '', 'noun', 'beginner'),
('káasùwà', 'market', '', 'noun', 'intermediate'),
('shə̀əd', 'morning', '', 'noun', 'beginner'),
('ɗìyò', 'marriage', '', 'noun', 'intermediate'),
('ɗìikó', 'mortar', '', 'noun', 'intermediate'),
('tɔ̀k', 'mat', '', 'noun', 'intermediate'),
('pèrèt', 'mosquito', '', 'noun', 'beginner'),
('nìyò', 'mature', '', 'verb', 'intermediate'),
('nɔ̀nnɔ́', 'mother', '', 'noun', 'beginner'),
('kèrò', 'measure', '', 'verb', 'intermediate'),
('mòllà nɔ̀nnɔ́', 'mothers sister', '', 'noun', 'intermediate'),
('lɔ̀ɔ', 'meat', '', 'noun', 'beginner'),
('fɔ̀k', 'mouth', '', 'noun', 'beginner'),
('ʔàn tùɣ nìnyò', 'murderer', '', 'noun', 'advanced'),

-- N entries
('shɔ̀mmɔ̀', 'name', '', 'noun', 'beginner'),
('ɓàkà', 'natron', '', 'noun', 'advanced'),
('ʔàlúurà', 'needle', '', 'noun', 'intermediate'),
('kúmmí', 'navel', '', 'noun', 'beginner'),
('nìmmì', 'near', '', 'adverb', 'beginner'),
('gbɔ́ŋ', 'neck', '', 'noun', 'beginner'),
('fɔ̀ɣèràw', 'nine', '', 'number', 'beginner'),
('kà dàràŋ', 'noon', '', 'noun', 'intermediate'),
('làɗì', 'north', '', 'noun', 'intermediate'),

-- O entries
('mɔ̀r', 'oil', '', 'noun', 'beginner'),
('pámmò', 'ordeal', '', 'noun', 'advanced'),
('ʔáɓùrùl', 'okra', '', 'noun', 'intermediate'),
('gbáláŋ', 'ornament', '', 'noun', 'intermediate'),
('kù', 'on', '', 'preposition', 'beginner'),
('làkà', 'orphan', '', 'noun', 'intermediate'),
('ɗɔ̀k', 'one', '', 'number', 'beginner'),
('péewé', 'outside', '', 'adverb', 'intermediate'),
('ʔàrùm', 'onion', '', 'noun', 'intermediate'),
('mìigù', 'owl', '', 'noun', 'intermediate'),
('mínná kə̀nímmà', 'oracle', '', 'noun', 'advanced'),

-- P entries
('mínná gùp', 'palace', '', 'noun', 'advanced'),
('jêy', 'porcupine', '', 'noun', 'intermediate'),
('shègré', 'past', '', 'noun', 'advanced'),
('dìgré', 'pot', '', 'noun', 'intermediate'),
('góndà', 'pawpaw', '', 'noun', 'intermediate'),
('ɗíyè', 'pot', '', 'noun', 'intermediate'),
('árí', 'pea', '', 'noun', 'intermediate'),
('télàŋ', 'pot', '', 'noun', 'intermediate'),
('ʔàn shìráw', 'peasant', '', 'noun', 'intermediate'),
('kùwò', 'penis', '', 'noun', 'beginner'),
('ʔàn ɗíyè', 'potter', '', 'noun', 'intermediate'),
('mìmé', 'people', '', 'noun', 'beginner'),
('dìishò', 'pound', '', 'verb', 'intermediate'),
('ʔànshìndáw', 'pepper', '', 'noun', 'intermediate'),
('vúró', 'powder', '', 'noun', 'intermediate'),
('nìŋò', 'person', '', 'noun', 'beginner'),
('ʔùn', 'pregnancy', '', 'noun', 'intermediate'),
('gbáŋlàŋ', 'pestle', '', 'noun', 'intermediate'),
('ʔàn gùnùl', 'priest', '', 'noun', 'advanced'),
('ʔàládè', 'pig', '', 'noun', 'intermediate'),
('ríibà', 'profit', '', 'noun', 'intermediate'),
('ɗòorò', 'pipe', '', 'noun', 'intermediate'),
('vɔ̀ɔn', 'pumpkin', '', 'noun', 'intermediate'),
('shèewò', 'plant', '', 'verb', 'intermediate'),
('fòoró', 'punishment', '', 'noun', 'intermediate'),
('fɔ̀ɗɗɔ̀', 'pluck out', '', 'verb', 'intermediate'),
('lí', 'put', '', 'verb', 'beginner'),
('shèmù', 'poison', '', 'noun', 'intermediate'),
('rêw', 'python', '', 'noun', 'intermediate'),
('kènnì', 'poor', '', 'adjective', 'intermediate'),

-- R entries
('ŋɔ̀rì', 'rainbird', '', 'noun', 'advanced'),
('jìkò', 'rich', '', 'adjective', 'intermediate'),
('màlàc', 'rainbow', '', 'noun', 'intermediate'),
('ʔàmmò', 'ride horse', '', 'verb', 'intermediate'),
('ʔàn kə̀nímmà', 'rainmaker', '', 'noun', 'advanced'),
('témmè2', 'right', '', 'adverb', 'beginner'),
('gàlmà', 'ram', '', 'noun', 'intermediate'),
('èm', 'ring', '', 'noun', 'intermediate'),
('dàmàl', 'rat', '', 'noun', 'intermediate'),
('shúrùk', 'river', '', 'noun', 'intermediate'),
('gàrìnjìn', 'rat', '', 'noun', 'intermediate'),
('fɔ̀ shúrùk', 'riverbank', '', 'noun', 'intermediate'),
('shìwrì', 'rat', '', 'noun', 'intermediate'),
('kɔ́ɣɔ́', 'road', '', 'noun', 'intermediate'),
('ʔàllágà', 'rat', '', 'noun', 'intermediate'),
('shìilà', 'rock', '', 'noun', 'intermediate'),
('ʔàyùkh', 'rat', '', 'noun', 'intermediate'),
('ɓwáré', 'rattle', '', 'noun', 'intermediate'),
('kù mínná', 'roof', '', 'noun', 'intermediate'),
('gàɣàl', 'red', '', 'adjective', 'beginner'),
('gùmè', 'room', '', 'noun', 'beginner'),
('mòlón', 'relative', '', 'noun', 'intermediate'),
('shóorím', 'root', '', 'noun', 'intermediate'),
('nèsshò', 'rest', '', 'verb', 'intermediate'),
('fúulá', 'rope', '', 'noun', 'intermediate'),
('jèrà gɔ̀ŋɔ̀', 'ribs', '', 'noun', 'intermediate'),
('dòɣbɔ́', 'ruin', '', 'noun', 'intermediate'),
('gàpà', 'rice', '', 'noun', 'intermediate'),
('làllò', 'ruminate', '', 'verb', 'advanced'),

-- S entries
('wàw', 'sacrifice', '', 'noun', 'intermediate'),
('kpèyù', 'snake', '', 'noun', 'intermediate'),
('kúrét', 'snake', '', 'noun', 'intermediate'),
('ʔànjà', 'salt', '', 'noun', 'beginner'),
('jìwò', 'snare', '', 'verb', 'intermediate'),
('lùmmò ɓùk', 'sand', '', 'noun', 'intermediate'),
('ɓùk', 'soil', '', 'noun', 'beginner'),
('shwìyàk', 'sand', '', 'noun', 'intermediate'),
('là', 'son', '', 'noun', 'beginner'),
('jwál fírǎ', 'scar', '', 'noun', 'intermediate'),
('vònàk', 'song', '', 'noun', 'beginner'),
('áɗéŋré', 'scorpion', '', 'noun', 'intermediate'),
('dìmlìm', 'soot', '', 'noun', 'intermediate'),
('péèn', 'seed', '', 'noun', 'intermediate'),
('ʔàn shɔ̀ɔ', 'sorcerer', '', 'noun', 'advanced'),
('là mínná', 'servant', '', 'noun', 'intermediate'),
('pírá', 'sore', '', 'noun', 'intermediate'),
('khèeyàw', 'sesame', '', 'noun', 'intermediate'),
('vìyè', 'sauce', '', 'noun', 'beginner'),
('láɗú', 'sesame', '', 'noun', 'intermediate'),
('dàŋ', 'south', '', 'noun', 'intermediate'),
('vànà', 'sesame', '', 'noun', 'intermediate'),
('kàawò', 'sow', '', 'verb', 'intermediate'),
('árkyaw', 'sesame', '', 'noun', 'intermediate'),
('tòbbò', 'sow', '', 'verb', 'intermediate'),
('fàrlów', 'seven', '', 'number', 'beginner'),
('kàsh', 'spear', '', 'noun', 'intermediate'),
('tònnò', 'sew', '', 'verb', 'intermediate'),
('láalá', 'spider', '', 'noun', 'intermediate'),
('lùgnì', 'shade', '', 'noun', 'intermediate'),
('dòodó', 'spirit', '', 'noun', 'advanced'),
('shéwó', 'shame', '', 'noun', 'intermediate'),
('jìrìm', 'spirit', '', 'noun', 'advanced'),
('dìnyì', 'sheep', '', 'noun', 'intermediate'),
('vìyò', 'spirit', '', 'noun', 'advanced'),
('gɔ̀ɣlɔ̀', 'shell', '', 'noun', 'intermediate'),
('jèdè', 'shield', '', 'noun', 'intermediate'),
('júr', 'squirrel', '', 'noun', 'intermediate'),
('sháwán', 'shield', '', 'noun', 'intermediate'),
('ʔàŋ gèerù téré', 'star', '', 'noun', 'intermediate'),
('shúŋúr', 'shinbone', '', 'noun', 'intermediate'),
('ʔàrshàl', 'star', '', 'noun', 'intermediate'),
('tàa', 'shoe', '', 'noun', 'beginner'),
('bèe', 'shoot', '', 'verb', 'intermediate'),
('shìwòn', 'shrew', '', 'noun', 'advanced'),
('tèmèl', 'shoulder', '', 'noun', 'beginner'),
('fɔ̀də́mlì', 'sickle', '', 'noun', 'intermediate'),
('tà áà', 'stomach', '', 'noun', 'beginner'),
('ɣèlà', 'side', '', 'noun', 'intermediate'),
('pìrìt dòo', 'storm', '', 'noun', 'intermediate'),
('dèy', 'sinew', '', 'noun', 'advanced'),
('bìnnò', 'stranger', '', 'noun', 'intermediate'),
('ʔàn vònàk', 'singer', '', 'noun', 'intermediate'),
('jùjákh', 'straw', '', 'noun', 'intermediate'),
('mòllà', 'sister', '', 'noun', 'beginner'),
('ɓáŋ', 'strength', '', 'noun', 'intermediate'),
('fàràgbànàŋ', 'six', '', 'number', 'beginner'),
('gbáarò', 'strip off', '', 'verb', 'intermediate'),
('shùnò', 'skin', '', 'verb', 'intermediate'),
('láɣát', 'skin (body)', '', 'noun', 'beginner'),
('dàràŋ', 'sun', '', 'noun', 'beginner'),
('màŋlàŋ', 'skull', '', 'noun', 'intermediate'),
('dàràŋ dén', 'sunshine', '', 'noun', 'intermediate'),
('shàɣlò', 'sleep', '', 'noun', 'beginner'),
('tà gə̀də̀', 'slope', '', 'noun', 'intermediate'),
('ʔòshò', 'swell', '', 'verb', 'intermediate'),
('dùŋò', 'smoke', '', 'noun', 'intermediate'),
('ʔàngárùm', 'sword', '', 'noun', 'intermediate'),

-- T entries
('gìrìr', 'tail', '', 'noun', 'beginner'),
('kpàanò', 'tan', '', 'verb', 'intermediate'),
('ʔàn kpáanì', 'tanner', '', 'noun', 'intermediate'),
('gàndù', 'tax', '', 'noun', 'intermediate'),
('kpòmù', 'ten', '', 'number', 'beginner'),
('khàyukh', 'termite', '', 'noun', 'intermediate'),
('shìɓɔ̀ gə̀də̀', 'terrace', '', 'noun', 'advanced'),
('ʔàr shíilì', 'testicles', '', 'noun', 'beginner'),
('fɔ̀ tèerè', 'there', '', 'adverb', 'beginner'),
('fɔ̀shénnì', 'there', '', 'adverb', 'beginner'),
('jírí', 'thief', '', 'noun', 'intermediate'),
('fìnnè', 'thigh', '', 'noun', 'beginner'),
('ìshì fɔ̀k', 'thirst', '', 'noun', 'intermediate'),
('ʔàràt', 'thorn', '', 'noun', 'intermediate'),
('dùbù', 'thousand', '', 'number', 'intermediate'),
('tàat', 'three', '', 'number', 'beginner'),
('shúurò shàw', 'threshing', '', 'noun', 'intermediate'),
('gòoròk', 'throat', '', 'noun', 'beginner'),
('náanì', 'thunder', '', 'noun', 'intermediate'),
('tùkkò', 'tie', '', 'verb', 'beginner'),
('ɗímím', 'time', '', 'noun', 'intermediate'),
('ɓálá', 'tiredness', '', 'noun', 'intermediate'),
('dànyùkh', 'toad', '', 'noun', 'intermediate'),
('tàawa', 'tobacco', '', 'noun', 'intermediate'),
('ɓwòy', 'today', '', 'noun', 'beginner'),
('kùurò dɔ̀ɔ', 'tomato', '', 'noun', 'beginner'),
('kùurò', 'tomato', '', 'noun', 'beginner'),
('ɗwèy', 'tomorrow', '', 'noun', 'beginner'),
('ɗák', 'tongue', '', 'noun', 'beginner'),
('khɔ́ɣɔ́', 'track', '', 'noun', 'intermediate'),
('bàrà', 'trap', '', 'noun', 'intermediate'),
('mèrà', 'travel', '', 'noun', 'intermediate'),
('bìró', 'tree', '', 'noun', 'beginner'),
('jèshílè', 'trumpet', '', 'noun', 'intermediate'),
('ɓòŋ bìró', 'trunk', '', 'noun', 'intermediate'),
('tɔ̀lɔ́tɔ̀lɔ́', 'turkey', '', 'noun', 'intermediate'),
('ròmìsh', 'twin', '', 'noun', 'intermediate'),
('pə̀llɔ̀w', 'two', '', 'number', 'beginner'),

-- U entries
('fɔ̀nnò', 'uncle', '', 'noun', 'beginner'),
('gùm', 'under', '', 'preposition', 'beginner'),
('ɓwèyù', 'underworld', '', 'noun', 'advanced'),
('ʔàníyùm', 'unripe', '', 'adjective', 'intermediate'),

-- V entries
('gbàk', 'vagina', '', 'noun', 'beginner'),
('shàmmàm', 'viper', '', 'noun', 'intermediate'),
('tà shúrùk', 'valley', '', 'noun', 'intermediate'),
('élé', 'voice', '', 'noun', 'beginner'),
('kɔ́ɣɔ́ dàm', 'vein', '', 'noun', 'intermediate'),
('shèllè', 'vulture', '', 'noun', 'intermediate'),

-- W entries
('shí mínná', 'wall', '', 'noun', 'intermediate'),
('gèy', 'war', '', 'noun', 'intermediate'),
('ʔàn tòom', 'warrior', '', 'noun', 'intermediate'),
('fùɗɗɔ̀', 'wash', '', 'verb', 'beginner'),
('jɔ̀k', 'wasp', '', 'noun', 'intermediate'),
('méemé', 'wasp', '', 'noun', 'intermediate'),
('dòo', 'water', '', 'noun', 'beginner'),
('shàrgey', 'weapon', '', 'noun', 'intermediate'),
('tònnò', 'weave', '', 'verb', 'intermediate'),
('ʔàn láddò', 'weaver', '', 'noun', 'intermediate'),
('ríijà', 'well', '', 'noun', 'intermediate'),
('tàvrò', 'west', '', 'noun', 'intermediate'),
('ɗúulàn', 'wet', '', 'adjective', 'beginner'),
('ɗímmín', 'when?', '', 'interrogative', 'beginner'),
('tìtɔ́ŋ', 'where?', '', 'interrogative', 'beginner'),
('pè', 'white', '', 'adjective', 'beginner'),
('kɔ̀lɔ̀', 'widow', '', 'noun', 'intermediate'),
('pìrìt', 'wind', '', 'noun', 'beginner'),
('ɓàakh', 'wing(s)', '', 'noun', 'intermediate'),
('ʔàn wɔ̀lɔ̀', 'witch', '', 'noun', 'advanced'),
('shìrìp', 'woman', '', 'noun', 'beginner'),
('shùwè', 'wood', '', 'noun', 'intermediate'),
('kù péewè', 'world', '', 'noun', 'advanced'),
('jìwúr', 'worm', '', 'noun', 'intermediate'),
('téelè', 'worship', '', 'noun', 'advanced'),
('fòɗùlò', 'wound', '', 'verb', 'intermediate'),
('khà', 'wound', '', 'verb', 'intermediate'),

-- X, Y entries
('gájágí', 'xylophone', '', 'noun', 'intermediate'),
('shányè', 'yam(s)', '', 'noun', 'intermediate'),
('shènè', 'year', '', 'noun', 'beginner'),
('kpòolɔ́', 'yesterday', '', 'noun', 'beginner');