-- Insert new Goji dictionary entries batch 3
INSERT INTO dictionary_entries (
  goji_word, 
  english_translation, 
  hausa_translation, 
  example_sentence, 
  cultural_context, 
  part_of_speech,
  difficulty_level,
  contribution_id,
  contributor_id,
  approved_at
) VALUES 
-- L entries
('là', 'child, son', 'ɗa', NULL, 'Plural: shíbó, cíbó', 'n', 'beginner', gen_random_uuid(), gen_random_uuid(), now()),
('láɣát (shìk)', 'skin (body)', 'fatar jiki', NULL, NULL, 'n', 'beginner', gen_random_uuid(), gen_random_uuid(), now()),
('là gèɣè', 'bride (girl not married)', NULL, NULL, NULL, 'n', 'intermediate', gen_random_uuid(), gen_random_uuid(), now()),
('láját', 'outfit of hunter', 'rigar mafarauci', NULL, NULL, 'n', 'intermediate', gen_random_uuid(), gen_random_uuid(), now()),
('là ɗúndì', 'small bottle gourd', 'buta', NULL, NULL, 'n', 'intermediate', gen_random_uuid(), gen_random_uuid(), now()),
('làkà', 'orphan', 'maraya', NULL, NULL, 'n', 'intermediate', gen_random_uuid(), gen_random_uuid(), now()),
('là gàráyà', 'musical bow', 'izga', NULL, NULL, 'n', 'intermediate', gen_random_uuid(), gen_random_uuid(), now()),
('làllò', 'ruminate', 'ci (saniya)', NULL, NULL, 'v', 'intermediate', gen_random_uuid(), gen_random_uuid(), now()),
('là mínná', 'servant', 'bara, barabya', NULL, 'Literally: boy (of) house', 'n', 'intermediate', gen_random_uuid(), gen_random_uuid(), now()),
('làmbú', 'garden', 'gadina, lamu', NULL, NULL, 'n', 'beginner', gen_random_uuid(), gen_random_uuid(), now()),
('lànnà', 'clothes', 'tufafi', NULL, NULL, 'n', 'beginner', gen_random_uuid(), gen_random_uuid(), now()),
('là shìrìp', 'daughter', 'ya mace, ɗiya', NULL, 'Plural: cíbó shìrìp', 'n', 'beginner', gen_random_uuid(), gen_random_uuid(), now()),
('lèeláw', 'cotton', 'auduga', NULL, NULL, 'n', 'intermediate', gen_random_uuid(), gen_random_uuid(), now()),
('là shúrùk', 'seasonal river', 'kogi', NULL, NULL, 'n', 'intermediate', gen_random_uuid(), gen_random_uuid(), now()),
('léɣá', 'desire', 'shaʔawa', NULL, NULL, 'n', 'intermediate', gen_random_uuid(), gen_random_uuid(), now()),
('là shùɣì', 'boy, son', 'ɗa', NULL, 'Plural: cíbó shùɣì', 'n', 'beginner', gen_random_uuid(), gen_random_uuid(), now()),
('lèwɔ̀', 'want, like, love', 'so', NULL, NULL, 'v', 'beginner', gen_random_uuid(), gen_random_uuid(), now()),
('là tálàŋ', 'pot for cooking soup', 'tukunya', NULL, NULL, 'n', 'intermediate', gen_random_uuid(), gen_random_uuid(), now()),
('lí', 'put', 'sa', NULL, NULL, 'v', 'beginner', gen_random_uuid(), gen_random_uuid(), now()),
('là témmè', 'calabash for drinking beer', 'duma', NULL, NULL, 'n', 'intermediate', gen_random_uuid(), gen_random_uuid(), now()),
('lìlámdè', 'butterfly', 'malam-buɗa-mana-littafi', NULL, NULL, 'n', 'beginner', gen_random_uuid(), gen_random_uuid(), now()),
('láalá', 'spider', 'gizo-gizo', NULL, 'mínná láalá = cobweb', 'n', 'beginner', gen_random_uuid(), gen_random_uuid(), now()),
('lɔ̀ɔ', 'meat', 'nama', NULL, 'lɔ̀(ɔ) tà shwè = bush meat (naman daji)', 'n', 'beginner', gen_random_uuid(), gen_random_uuid(), now()),
('láayá', 'charm', 'laya', NULL, NULL, 'n', 'intermediate', gen_random_uuid(), gen_random_uuid(), now()),
('lúrú', 'bag', 'jaka', NULL, NULL, 'n', 'beginner', gen_random_uuid(), gen_random_uuid(), now()),
('láɗú', 'grey sesame', 'riɗi', NULL, NULL, 'n', 'intermediate', gen_random_uuid(), gen_random_uuid(), now()),
('lùgnì', 'shade', 'inuwa', NULL, NULL, 'n', 'beginner', gen_random_uuid(), gen_random_uuid(), now()),
('làɗì', 'north', 'arewa', NULL, NULL, 'n', 'beginner', gen_random_uuid(), gen_random_uuid(), now()),
('lùmmò', 'flour', 'gari', NULL, NULL, 'n', 'beginner', gen_random_uuid(), gen_random_uuid(), now()),
('láɣát', 'leather, skin (animal)', 'fata (dabba)', NULL, NULL, 'n', 'beginner', gen_random_uuid(), gen_random_uuid(), now()),
('lùmmò ɓùk', 'fine sand', 'rairayi', NULL, NULL, 'n', 'intermediate', gen_random_uuid(), gen_random_uuid(), now()),

-- M entries
('màlàc', 'rainbow', 'bakan gizo', NULL, NULL, 'n', 'beginner', gen_random_uuid(), gen_random_uuid(), now()),
('mínná', 'house', 'gida', NULL, NULL, 'n', 'beginner', gen_random_uuid(), gen_random_uuid(), now()),
('màlàc dòo', 'rainbow', 'bakan gizo', NULL, 'See: màlàc', 'n', 'beginner', gen_random_uuid(), gen_random_uuid(), now()),
('mínná gùp', 'palace', 'gidan sarki', NULL, NULL, 'n', 'intermediate', gen_random_uuid(), gen_random_uuid(), now()),
('màlɣò', 'lightning', 'walƙiya', NULL, NULL, 'n', 'beginner', gen_random_uuid(), gen_random_uuid(), now()),
('mínná kə̀nímmà', 'oracle', NULL, NULL, NULL, 'n', 'advanced', gen_random_uuid(), gen_random_uuid(), now()),
('màmmà', 'ant-hill', 'jiɓa, suri, shuri', NULL, NULL, 'n', 'intermediate', gen_random_uuid(), gen_random_uuid(), now()),
('mòɗɗò', 'millet', 'gero', NULL, NULL, 'n', 'beginner', gen_random_uuid(), gen_random_uuid(), now()),
('màŋlàŋ', 'skull', 'ƙwaƙwalwa, kwanya', NULL, NULL, 'n', 'intermediate', gen_random_uuid(), gen_random_uuid(), now()),
('mòllò', 'brother', 'ƙane', NULL, NULL, 'n', 'beginner', gen_random_uuid(), gen_random_uuid(), now()),
('mánná', 'husband', 'miji', NULL, NULL, 'n', 'beginner', gen_random_uuid(), gen_random_uuid(), now()),
('mòllà', 'sister', NULL, NULL, 'mòllà nɔ̀nnɔ́ = mother''s sister', 'n', 'beginner', gen_random_uuid(), gen_random_uuid(), now()),
('mə̀n', 'beer', 'giya', NULL, NULL, 'n', 'intermediate', gen_random_uuid(), gen_random_uuid(), now()),
('mòlón', 'relative', 'dangi', NULL, NULL, 'n', 'beginner', gen_random_uuid(), gen_random_uuid(), now()),
('mə̀n ɗíyè', 'beer pot', 'tulun giya', NULL, NULL, 'n', 'intermediate', gen_random_uuid(), gen_random_uuid(), now()),
('mɔ̀n tùɣànò', 'drunk', 'bugagge', NULL, 'Literally: beer killed me', 'n, adj', 'intermediate', gen_random_uuid(), gen_random_uuid(), now()),
('mè àn', 'many', 'da yawa', NULL, NULL, 'adv', 'beginner', gen_random_uuid(), gen_random_uuid(), now()),
('méemé', 'wasp', 'zanzaro', NULL, NULL, 'n', 'beginner', gen_random_uuid(), gen_random_uuid(), now()),
('Mèerò', 'make, braid rope', NULL, NULL, NULL, 'v', 'intermediate', gen_random_uuid(), gen_random_uuid(), now()),
('mɔ̀r', 'oil', 'mai', NULL, NULL, 'n', 'beginner', gen_random_uuid(), gen_random_uuid(), now()),
('mèrà', 'travel', 'tafiya', NULL, NULL, 'n', 'beginner', gen_random_uuid(), gen_random_uuid(), now()),
('mɔ̀r tàngà', 'butter', 'man shanu', NULL, NULL, 'n', 'intermediate', gen_random_uuid(), gen_random_uuid(), now()),
('mìɗò', 'stirring stick', 'muciya', NULL, NULL, 'n', 'intermediate', gen_random_uuid(), gen_random_uuid(), now()),
('móotò', 'car', 'mota', NULL, NULL, 'n', 'beginner', gen_random_uuid(), gen_random_uuid(), now()),
('mìigù', 'owl', 'mugiya', NULL, NULL, 'n', 'beginner', gen_random_uuid(), gen_random_uuid(), now()),
('múlkì', 'chieftancy', 'sarauta', NULL, NULL, 'n', 'advanced', gen_random_uuid(), gen_random_uuid(), now()),
('mìllán kpòolɔ́', 'last year', 'bara', NULL, NULL, 'adv', 'intermediate', gen_random_uuid(), gen_random_uuid(), now()),
('mùrɔ̀', 'die', 'mutu', NULL, NULL, 'v', 'beginner', gen_random_uuid(), gen_random_uuid(), now()),
('mìmé', 'people', 'mutane', NULL, NULL, 'n', 'beginner', gen_random_uuid(), gen_random_uuid(), now()),
('mùshì', 'jealousy', 'kishi', NULL, NULL, 'n', 'intermediate', gen_random_uuid(), gen_random_uuid(), now()),

-- N entries
('nàa', 'elephant', 'giwa', NULL, NULL, 'n', 'beginner', gen_random_uuid(), gen_random_uuid(), now()),
('nìŋò', 'person, man', 'mutum', NULL, 'Plural: mìmé', 'n', 'beginner', gen_random_uuid(), gen_random_uuid(), now()),
('nàa', 'particle used to form numerals', NULL, NULL, NULL, 'prt', 'intermediate', gen_random_uuid(), gen_random_uuid(), now()),
('nìŋòn dìn', 'black man', NULL, NULL, NULL, 'n', 'intermediate', gen_random_uuid(), gen_random_uuid(), now()),
('nàa tààt', 'thirty', 'talatin', NULL, NULL, 'num', 'intermediate', gen_random_uuid(), gen_random_uuid(), now()),
('nìŋòn gàràl', 'white man', 'bature', NULL, NULL, 'n', 'intermediate', gen_random_uuid(), gen_random_uuid(), now()),
('nàa fúwàt', 'fifty', 'hamsin', NULL, NULL, 'num', 'intermediate', gen_random_uuid(), gen_random_uuid(), now()),
('nìyò', 'mature, become ripe', 'nuna', NULL, NULL, 'v', 'intermediate', gen_random_uuid(), gen_random_uuid(), now()),
('náanì', 'thunder', 'hadari', NULL, NULL, 'n', 'beginner', gen_random_uuid(), gen_random_uuid(), now()),
('nɔ̀nnɔ́', 'mother', 'uwa', NULL, NULL, 'n', 'beginner', gen_random_uuid(), gen_random_uuid(), now()),
('nèsshò', 'rest', 'huta', NULL, NULL, 'v', 'beginner', gen_random_uuid(), gen_random_uuid(), now()),
('ŋɔ̀rì', 'rainbird', NULL, NULL, NULL, 'n', 'intermediate', gen_random_uuid(), gen_random_uuid(), now()),
('nèy', 'fight', 'faɗa', NULL, NULL, 'n', 'beginner', gen_random_uuid(), gen_random_uuid(), now()),
('nùrò', 'heal', 'warke, warkar da', NULL, NULL, 'v', 'intermediate', gen_random_uuid(), gen_random_uuid(), now()),
('nìmmì', 'near', 'kusa', NULL, 'à nìmmìm = not near (ba kusa ba)', 'adv', 'beginner', gen_random_uuid(), gen_random_uuid(), now()),

-- O entries
('ɔ́ɣrɔ́', 'bottle', 'kwlaba', NULL, NULL, 'n', 'beginner', gen_random_uuid(), gen_random_uuid(), now()),
('ɔ̀ppɔ̀ dùwò', 'funeral', 'jana''iza', NULL, 'Literally: digging grave', 'n', 'intermediate', gen_random_uuid(), gen_random_uuid(), now()),
('ɔ̀ppɔ̀', 'dig', 'haƙa', NULL, NULL, 'v', 'beginner', gen_random_uuid(), gen_random_uuid(), now()),
('òshò', 'swell', 'kumbura', NULL, NULL, 'v', 'intermediate', gen_random_uuid(), gen_random_uuid(), now()),

-- P entries
('pámmò', 'ordeal', NULL, NULL, NULL, 'n', 'advanced', gen_random_uuid(), gen_random_uuid(), now()),
('péewé', 'outside', 'waje', NULL, NULL, 'adv', 'beginner', gen_random_uuid(), gen_random_uuid(), now()),
('pàrɔ̀', 'herd (animals)', NULL, NULL, NULL, 'v', 'intermediate', gen_random_uuid(), gen_random_uuid(), now()),
('pèrèt', 'mosquito', 'sauro', NULL, NULL, 'n', 'beginner', gen_random_uuid(), gen_random_uuid(), now()),
('pàttò', 'give birth', 'haifa', NULL, NULL, 'v', 'beginner', gen_random_uuid(), gen_random_uuid(), now()),
('pèrɔ̀', 'go out', 'fita', NULL, NULL, 'v', 'beginner', gen_random_uuid(), gen_random_uuid(), now()),
('pə̀ək', 'lungs', 'huhu', NULL, NULL, 'n', 'intermediate', gen_random_uuid(), gen_random_uuid(), now()),
('pìdìɗòw', 'eight', 'takwas', NULL, NULL, 'num', 'beginner', gen_random_uuid(), gen_random_uuid(), now()),
('pə̀əmún', 'female, wife', 'mace', NULL, 'Plural: shìrìp', 'n', 'beginner', gen_random_uuid(), gen_random_uuid(), now()),
('pìl', 'hook', 'ƙugiya', NULL, NULL, 'n', 'intermediate', gen_random_uuid(), gen_random_uuid(), now()),
('pə̀llɔ̀w', 'two', 'biyu', NULL, NULL, 'num', 'beginner', gen_random_uuid(), gen_random_uuid(), now()),
('pírá', 'sore, wound, disease', 'rauni', NULL, NULL, 'n', 'intermediate', gen_random_uuid(), gen_random_uuid(), now()),
('pè', 'white', 'fari', NULL, NULL, 'adj', 'beginner', gen_random_uuid(), gen_random_uuid(), now()),
('pìrìt', 'wind', 'iska', NULL, NULL, 'n', 'beginner', gen_random_uuid(), gen_random_uuid(), now()),
('péèn', 'seed', NULL, NULL, NULL, 'n', 'beginner', gen_random_uuid(), gen_random_uuid(), now()),
('pìrìt dòo', 'storm', 'ruwa da iska', NULL, NULL, 'n', 'intermediate', gen_random_uuid(), gen_random_uuid(), now()),
('péeròw', 'four', 'huɗu', NULL, NULL, 'num', 'beginner', gen_random_uuid(), gen_random_uuid(), now()),
('pìrù', 'come out', 'fito', NULL, NULL, 'v', 'beginner', gen_random_uuid(), gen_random_uuid(), now()),

-- R entries
('ràagúmì', 'camel', 'raƙumi', NULL, NULL, 'n', 'beginner', gen_random_uuid(), gen_random_uuid(), now()),
('réy', 'life', 'rai', NULL, NULL, 'n', 'beginner', gen_random_uuid(), gen_random_uuid(), now()),
('rèeké', 'sugar cane', 'kara', NULL, NULL, 'n', 'beginner', gen_random_uuid(), gen_random_uuid(), now()),
('ríibà', 'profit', 'riba', NULL, NULL, 'n', 'intermediate', gen_random_uuid(), gen_random_uuid(), now()),
('rêw', 'python', 'mesa', NULL, 'See: kúrét, shàmmàm', 'n', 'intermediate', gen_random_uuid(), gen_random_uuid(), now()),
('ríijà', 'well', 'rijiya', NULL, NULL, 'n', 'beginner', gen_random_uuid(), gen_random_uuid(), now()),
('rə́wák', 'baboon', 'gwaggon biri', NULL, NULL, 'n', 'intermediate', gen_random_uuid(), gen_random_uuid(), now()),
('ríwít', 'fire-place', 'wurin wuta', NULL, NULL, 'n', 'intermediate', gen_random_uuid(), gen_random_uuid(), now()),
('rè', 'enter', 'shiga', NULL, NULL, 'v', 'beginner', gen_random_uuid(), gen_random_uuid(), now()),
('ròmìsh', 'twin', 'ɗan tagwai', NULL, NULL, 'n', 'intermediate', gen_random_uuid(), gen_random_uuid(), now());