-- Add second batch of Goji dictionary entries (68 words)
INSERT INTO dictionary_entries (
  contribution_id,
  contributor_id,
  goji_word,
  english_translation,
  hausa_translation,
  part_of_speech,
  difficulty_level,
  usage_frequency,
  created_at,
  approved_at
)
SELECT 
  c.id as contribution_id,
  c.user_id as contributor_id,
  entries.goji_word,
  entries.english_translation,
  entries.hausa_translation,
  entries.part_of_speech,
  'beginner' as difficulty_level,
  0 as usage_frequency,
  now() as created_at,
  now() as approved_at
FROM (SELECT id, user_id FROM contributions WHERE goji_text = 'System Import' LIMIT 1) c
CROSS JOIN (VALUES
  ('gàaɣá', 'grandmother', 'kaka', 'n.'),
  ('gbàarò', 'strip off', 'tuɓe', 'v.'),
  ('gàakh', 'crow', 'hankaka', 'n.'),
  ('gɓàalò', 'throw a spear', 'jefa mashi', 'v.'),
  ('gàalé', 'water storage pot', 'randa', 'n.'),
  ('gèe', 'used to form numerals', '', 'prt.'),
  ('gèe ɗɔ̀k', 'eleven', 'goma sha ɗaya', 'num.'),
  ('gààrè', 'robe (man''s gown)', 'riga', 'n.'),
  ('gàarì', 'flea', 'ƙuma, tunkuyau', 'n.'),
  ('gènó', 'mother''s brother', 'wa', 'n.'),
  ('gàɣàl', 'red', 'ja', 'adj.'),
  ('gə̀rùm', 'molar', 'matauni', 'n.'),
  ('gájágí', 'xylophone', 'balanho', 'n.'),
  ('gètè', 'hawk, eagle', 'shaho', 'n.'),
  ('gàlmà', 'ram', 'rago', 'n.'),
  ('gèy', 'war', 'yaƙi', 'n.'),
  ('gáŋà', 'basket', 'kwando', 'n.'),
  ('gìrbì', 'donkey', 'jaki', 'n.'),
  ('gàndù', 'tax', 'haraji', 'n.'),
  ('gìrìr', 'tail', 'wutsiya', 'n.'),
  ('gàŋgàŋ', 'drum', 'ganga', 'n.'),
  ('gódó', 'blanket', 'bargo', 'n.'),
  ('gàŋrùŋ', 'world or place of dead', '', 'n.'),
  ('gòkh', 'cock', 'zakara', 'n.'),
  ('gàpà', 'rice', 'shinkafa', 'n.'),
  ('góndà', 'pawpaw', 'gwanda', 'n.'),
  ('gàráyà', 'string instruments', 'tsirkiya', 'n.'),
  ('gɔ̀ɣlɔ̀', 'shell', 'ƙwanso', 'n.'),
  ('gàrìnjìn', 'white rat', 'farin ɓera', 'n.'),
  ('gɔ̀lɔ̀m', 'grasshopper', 'fara', 'n.'),
  ('gàsshò', 'find', 'samu', 'v.'),
  ('gɔ̀ŋlàŋ', 'date', 'dabino', 'n.'),
  ('gbàaɣò', 'hollow out, carve wood', 'sassaƙa', 'v.'),
  ('gɔ̀ŋɔ̀', 'belly', 'ciki', 'n.'),
  ('gbàamé', 'axe', 'gatari', 'n.'),
  ('gòoròk', 'throat', 'maƙogwaro', 'n.'),
  ('gbàk', 'vagina', 'farji', 'n.'),
  ('gúlá', 'drum stick', 'makaɗi', 'n.'),
  ('gbáláŋ', 'ornament', 'abin ado, kayan ado', 'n.'),
  ('gùlmà', 'accusation', 'tuhuma', 'n.'),
  ('gbáŋ', 'goodness, wellness', 'lafiya', 'n.'),
  ('gùm', 'under', 'ƙarƙashin', 'prep.'),
  ('gbáŋlàŋ', 'pestle', 'taɓarya', 'n.'),
  ('gùmè', 'hut, room', 'ɗaki', 'n.'),
  ('gbáŋùm', 'unwell, sick', 'maras lafiya', 'adj.'),
  ('gùn', 'anus', 'dubura', 'n.'),
  ('gbàrìm', 'daughter or son in-law', 'sarakuwa', 'n.'),
  ('gùŋgúl', 'elbow', 'gwiwar hannu', 'n.'),
  ('gbárlàm', 'anklet', 'munduwa', 'n.'),
  ('gùngù', 'lame', 'gurgu', 'adj.'),
  ('gbàrùm', 'mother or father-in-law', 'suruki, suruka', 'n.'),
  ('gùnùl', 'ritual place', 'wuri na al''ada', 'n.'),
  ('gbáyákh', 'crop (bird)', 'maƙoƙo', 'n.'),
  ('gùp', 'chief, king, emir', 'sarki', 'n.'),
  ('gbé', 'big, senior', 'babba', 'adj.'),
  ('gùráŋ', 'calabash', 'duma, ƙwarya', 'n.'),
  ('gbìilì', 'chest', 'ƙirji', 'n.'),
  ('gùrùŋ', 'horse, mare, stallion', 'doki', 'n.'),
  ('gbɔ́ŋ', 'neck', 'wuya', 'n.'),
  ('gwàaja', 'cocoyam, taro', 'doya', 'n.'),
  ('gbɔ̀nnà', 'across', '(a) ƙetaren', 'prep.'),
  ('gwàŋ', 'food', 'abinci', 'n.'),
  ('gbɔ́shì', 'headpad', 'gammo', 'n.'),
  ('íshàn', 'dry, dried', 'use of verb ƙafe', 'adj.'),
  ('ìshì fɔ̀k', 'thirst', 'ƙishirwa', 'n.'),
  ('ìshì shwè', 'cornstalk', 'kara', 'n.'),
  ('ìshò', 'dry up', 'janye', 'v.'),
  ('ìshɔ̀', 'grind', 'ɓarza, niƙa', 'v.')
) AS entries(goji_word, english_translation, hausa_translation, part_of_speech)
WHERE NOT EXISTS (
  SELECT 1 FROM dictionary_entries de 
  WHERE de.goji_word = entries.goji_word
);