-- Add third batch of Goji dictionary entries (95 words)
INSERT INTO dictionary_entries (
  contribution_id,
  contributor_id,
  goji_word,
  english_translation,
  hausa_translation,
  part_of_speech,
  difficulty_level,
  usage_frequency,
  created_at,
  approved_at
)
SELECT 
  c.id as contribution_id,
  c.user_id as contributor_id,
  entries.goji_word,
  entries.english_translation,
  entries.hausa_translation,
  entries.part_of_speech,
  'beginner' as difficulty_level,
  0 as usage_frequency,
  now() as created_at,
  now() as approved_at
FROM (SELECT id, user_id FROM contributions WHERE goji_text = 'System Import' LIMIT 1) c
CROSS JOIN (VALUES
  ('jáɣlùm', 'cheek', 'kunci', 'n.'),
  ('jìkò', 'rich', 'mai arziki', 'n.'),
  ('jàmmó', 'loom', 'masaƙa', 'n.'),
  ('jìrà', 'bed', 'gado', 'n.'),
  ('jáŋ', 'jaw', 'mummuƙe', 'n.'),
  ('jírí', 'thief', 'ɓarawo', 'n.'),
  ('jàŋàní', 'leopard', 'damisa', 'n.'),
  ('jìrìm', 'spirit of a place', 'iska', 'n.'),
  ('jàrà', 'big basket for corn', 'kwando', 'n.'),
  ('jìró', 'red monkey', '', 'n.'),
  ('jàwéddà', 'small knife used for harvesting', '', 'n.'),
  ('jìwò', 'snare', 'zarge', 'v.'),
  ('jáwít', 'cutlery', 'wuƙa, cokali', 'n.'),
  ('jìwúr', 'worm', 'tsutsa', 'n.'),
  ('jèdè', 'shield', 'garkuwa', 'n.'),
  ('jìyaw', 'left', 'hagu', 'adv.'),
  ('jə̀ə', 'bean(s)', 'wake', 'n.'),
  ('jɔ̀d', 'filter', 'mataci', 'n.'),
  ('jèlà', 'side', '(a) hannu', 'n.'),
  ('jɔ̀k', 'black wasp', 'zanzaro', 'n.'),
  ('jéné', 'caterpillar', 'gizaka', 'n.'),
  ('jɔ́rrɔ́', 'locust', 'fara', 'n.'),
  ('jènè', 'dryness, aridity', 'rani', 'n.'),
  ('jùjákh', 'straw', 'haki', 'n.'),
  ('jènyè', 'crab', 'ƙaguwa', 'n.'),
  ('jùk', 'elephant', 'giwa', 'n.'),
  ('jèrà gɔ̀ŋɔ̀', 'ribs', 'haƙarƙari', 'n.'),
  ('jùk', 'chair', 'kujera', 'n.'),
  ('jèrè', 'friend, age-mate', 'aboki', 'n.'),
  ('jùŋrɔ̀ŋ', 'basket for corn', '', 'n.'),
  ('jèshílè', 'trumpet', 'kakaki', 'n.'),
  ('júr', 'squirrel', 'kurege', 'n.'),
  ('jêy', 'porcupine', 'beguwa', 'n.'),
  ('jùwò', 'jump', 'yi tsalle', 'v.'),
  ('jìi', 'place of burning', '', 'n.'),
  ('jwál', 'hole', '', 'n.'),
  ('jìijí', 'grandfather, ancestor', 'kaka, mutanen', 'n.'),
  ('jwál fírǎ', 'scar, notch', 'tabo', 'n.'),
  ('jwàlé', 'cricket', 'gyare', 'n.'),
  ('kàawò', 'sow', 'shuka', 'v.'),
  ('kɔ̀ɗɔ̀', 'claw', 'ƙambori', 'n.'),
  ('kà dàràŋ', 'daylight, noon', 'rana, tsakar rana', 'n.'),
  ('kɔ́ɣɔ́', 'road', 'hanya', 'n.'),
  ('káasùwà', 'market', 'kasuwa', 'n.'),
  ('kɔ́ɣɔ́ dàm', 'vein', 'jijiya', 'n.'),
  ('kàmmà', 'lion', 'zaki', 'n.'),
  ('kɔ̀lɔ̀', 'widow', 'bazawara', 'n.'),
  ('káŋ', 'granary', 'rumbu', 'n.'),
  ('kɔ̀n', 'judge', 'alƙali', 'n.'),
  ('kàr kúwò', 'circumcision', 'kaciya', 'n.'),
  ('kɔ̀ɔmɔ̀', 'maize', 'masara', 'n.'),
  ('káráráwá', 'bell', 'ƙarrarawa', 'n.'),
  ('kɔ̀shɔ̀', 'filter', 'tace', 'v.'),
  ('kàsh', 'spear', 'mashi', 'n.'),
  ('kpàa', 'horn', 'ƙaho', 'n.'),
  ('káshò', 'harvest', 'kaka', 'n.'),
  ('kpèyù', 'snake living in water', 'macijin ruwa', 'n.'),
  ('kàshò', 'harvest', 'gira, rora, cira, farta, tona', 'v.'),
  ('kàyò', 'hoe', 'yi noma', 'v.'),
  ('kpíshì', 'dust cloud', 'hadarin ƙura', 'n.'),
  ('kàyò táy', 'cut into pieces', 'yayyanka', 'v.'),
  ('kpòmù', 'ten', 'goma', 'num.'),
  ('kə́nə́', 'money', 'kuɗi', 'n.'),
  ('kpàanò', 'tan', 'jeme', 'v.'),
  ('kə̀rə̀k', 'border', 'iyaka', 'n.'),
  ('kpòolɔ́', 'yesterday', 'jiya', 'n.'),
  ('kə̀nímmà', 'fetish', 'juju', 'n.'),
  ('kù', 'on', 'a kan', 'prep.'),
  ('kèlà', 'monitor lizard', 'damo; guza; tsari', 'n.'),
  ('kù dàŋ', 'sky, heaven', 'sama, Aljanna', 'n.'),
  ('kènè ɗìyò', 'cowrie', 'wuri', 'n.'),
  ('kù mínná', 'roof', 'jinka', 'n.'),
  ('kènnì', 'poor', 'matalauci', 'n.'),
  ('kùɓùk', 'land, ground', 'ƙasa', 'n.'),
  ('kérákh', 'mahogany tree', 'maɗaci', 'n.'),
  ('kúmá', 'corpse', 'gawa', 'n.'),
  ('kèrè', 'roof of granary', 'jinkar rumbu', 'n.'),
  ('kúmmí', 'navel', 'cibiya', 'n.'),
  ('kèrèm', 'crocodile', 'kada', 'n.'),
  ('kúnná', 'dysentery', 'atuni', 'n.'),
  ('kèrò', 'measure', 'auna, gwada', 'v.'),
  ('kúmó', 'ear', 'kunne', 'n.'),
  ('khà', 'wound', 'yi wa rauni', 'v.'),
  ('kùmùm', 'doubt', 'shakka', 'n.'),
  ('kháa', 'gruel', 'kunu', 'n.'),
  ('kù péewè', 'world', 'duniya', 'n.'),
  ('khàyukh', 'termite', 'gara, gina, zago', 'n.'),
  ('khèeyàw', 'white sesame', 'riɗi', 'n.'),
  ('kúrét', 'snake', 'maciji', 'n.'),
  ('khèwnè', 'bush cow', 'saniya', 'n.'),
  ('shàmmàm', 'bitter tomato', 'gauta', 'n.'),
  ('khɔ́ɣɔ́', 'track', 'hanya', 'n.'),
  ('kùurò dɔ̀ɔ', 'type of bitter tomato (not dried)', 'ɗata', 'n.'),
  ('khù', 'head', 'kai', 'n.'),
  ('kùwò', 'lend', 'ranta, ara wa', 'v.'),
  ('khùrùwò', 'cowry', 'wuri', 'n.'),
  ('kùwò', 'penis', 'azzakari', 'n.'),
  ('kírá', 'arm, hand', 'hannu', 'n.'),
  ('kùwà', 'forge', 'maƙera', 'v.'),
  ('kírá bìró', 'branch', 'reshe', 'n.'),
  ('kùwák', 'curse', 'laʔana', 'n.'),
  ('kúwó', 'debt', 'bashi', 'n.'),
  ('kúyám', 'hunger', 'yunwa', 'n.'),
  ('kíríyípɔ́', 'dawn, evening', 'assalatu, asuba, maraice, yamma', 'n.')
) AS entries(goji_word, english_translation, hausa_translation, part_of_speech)
WHERE NOT EXISTS (
  SELECT 1 FROM dictionary_entries de 
  WHERE de.goji_word = entries.goji_word
);