-- Add batch 2 of Goji dictionary entries (71 words)
INSERT INTO dictionary_entries (
  goji_word, 
  english_translation, 
  hausa_translation, 
  part_of_speech, 
  semantic_category, 
  difficulty_level,
  contributor_id,
  contribution_id,
  approved_at,
  created_at
) VALUES 
-- B words
('bèe', 'shoot', 'harba', 'verb', 'actions', 'intermediate'),
('bànà', 'antelope', 'mazo, ragon ruwa, gwanki', 'noun', 'animals', 'beginner'),
('bàrà', 'trap', 'tarko', 'noun', 'tools', 'intermediate'),
('bèndè', 'penis sheath', 'gidan azzakari', 'noun', 'body', 'advanced'),
('bì', 'back, behind', 'baya', 'noun/prep', 'body/position', 'beginner'),
('bì bìró', 'bark of tree', 'ɓawo', 'noun', 'nature', 'intermediate'),
('bì gbɔ́ŋ', 'nape (of neck)', 'ƙeya', 'noun', 'body', 'intermediate'),
('bì shò', 'footprint', 'sawun ƙafa', 'noun', 'body', 'intermediate'),
('bìirìm', 'heel', 'diddige', 'noun', 'body', 'beginner'),
('bìlìr', 'flower', 'fure', 'noun', 'nature', 'beginner'),
('bìlìt', 'flower (variant)', 'fure', 'noun', 'nature', 'beginner'),
('bìndìgà', 'gun', 'bindiga', 'noun', 'tools', 'intermediate'),
('bìnnò', 'guest, stranger', 'baƙo', 'noun', 'social', 'beginner'),
('bìró', 'tree with no leaves', 'itace', 'noun', 'nature', 'beginner'),
('bùkwátì', 'bucket', 'bokiti', 'noun', 'tools', 'beginner'),

-- ɓ words
('ɓàakh', 'wing', 'fiffike', 'noun', 'animals', 'beginner'),
('ɓàkà', 'natron', '', 'noun', 'materials', 'advanced'),
('ɓálá', 'tiredness', 'gajiya', 'noun', 'feelings', 'beginner'),
('ɓáŋ', 'strength', 'ƙarfi', 'noun', 'qualities', 'beginner'),
('ɓán fɔ̀k', 'courage', 'jaruntaka', 'noun', 'qualities', 'intermediate'),
('ɓánnì', 'baobab tree', 'kuka', 'noun', 'nature', 'intermediate'),
('ɓày', 'dog', 'kare', 'noun', 'animals', 'beginner'),
('ɓə̀ək', 'wing(s)', 'fiffike', 'noun', 'animals', 'beginner'),
('ɓèrà', 'facial markings', 'sasshawa', 'noun', 'culture', 'intermediate'),
('ɓìrò', 'beat', 'buga', 'verb', 'actions', 'beginner'),
('ɓìr(ì) shàw', 'flail', '', 'noun', 'tools', 'advanced'),
('ɓòŋ bìró', 'trunk', 'gangar jiki', 'noun', 'nature', 'intermediate'),
('ɓɔ̀ɔlì', 'east', 'gabas', 'noun', 'directions', 'beginner'),
('ɓɔ̀rɔ̀n', 'type of millet', 'irin gero', 'noun', 'food', 'intermediate'),
('ɓùk', 'soil', 'ƙasa', 'noun', 'nature', 'beginner'),
('ɓwàarò ɗìyò', 'divorce', 'saki', 'noun', 'social', 'advanced'),
('ɓwáré', 'rattle', 'caki', 'noun', 'tools', 'intermediate'),
('ɓwèyù', 'underworld', '', 'noun', 'spiritual', 'advanced'),
('ɓwòy', 'today', 'yau', 'adverb', 'time', 'beginner'),

-- D words  
('dàbáŋ', 'festival', 'biki', 'noun', 'culture', 'beginner'),
('dìnyì', 'sheep', 'tunkiya', 'noun', 'animals', 'beginner'),
('nùn dìnyì', 'ewe', 'tunkiya', 'noun', 'animals', 'intermediate'),
('dàmàl', 'bushy tail', 'gafiya', 'noun', 'animals', 'intermediate'),
('dìráŋ', 'locust-bean tree', 'ɗorawa', 'noun', 'nature', 'intermediate'),
('dáŋ', 'door', 'ɗaki', 'noun', 'household', 'beginner'),
('dìishò', 'stamp, pound', 'daka', 'verb', 'actions', 'intermediate'),
('dàŋ1', 'south', 'kuda', 'noun', 'directions', 'beginner'),
('dòɣbɔ́', 'ruin', 'kango', 'noun', 'places', 'intermediate'),
('dàŋ2', 'above', 'kan, bisa da', 'preposition', 'position', 'beginner'),
('dòlòní', 'ant', 'kiyashi, cinnaka, tuma-da-gayya', 'noun', 'animals', 'beginner'),
('dànàm', 'sister-in-law', 'ƙanwa', 'noun', 'family', 'intermediate'),
('dòo', 'water', 'ruwa', 'noun', 'nature', 'beginner'),
('dàngà', 'fence', 'shinge', 'noun', 'household', 'beginner'),
('dòo wùrì', 'milk', 'nono', 'noun', 'food', 'beginner'),
('dànyùkh', 'frog, toad', 'kwaɗo', 'noun', 'animals', 'beginner'),
('dòodó', 'spirit', 'kurwa, aljani, iska', 'noun', 'spiritual', 'advanced'),
('dàràŋ', 'sun', 'rana', 'noun', 'nature', 'beginner'),
('dɔ̀ŋ', 'field, farm', 'gona', 'noun', 'places', 'beginner'),
('dàràŋ dén', 'sunshine', 'hasken rana', 'noun', 'nature', 'beginner'),
('dùbù', 'thousand', 'dubu', 'numeral', 'numbers', 'intermediate'),
('də̀ɓɓà', 'hyena', 'kura', 'noun', 'animals', 'intermediate'),
('dèet', 'fire', 'wuta', 'noun', 'nature', 'beginner'),
('dùŋò', 'smoke', 'hayaƙi', 'noun', 'nature', 'beginner'),
('dèwè', 'stick used to decorate pots', '', 'noun', 'tools', 'advanced'),
('dúmmò', 'hoe', 'fartanya, hauya', 'noun', 'tools', 'beginner'),
('dèy', 'sinew', 'agara', 'noun', 'body', 'advanced'),
('dùurò', 'bambara nut', 'gujiya', 'noun', 'food', 'intermediate'),
('dìgré', 'big storage pot', 'kwatarniya', 'noun', 'household', 'intermediate'),
('dùwò', 'ghost', 'fatalwa', 'noun', 'spiritual', 'advanced'),
('dìl bìró', 'forest', 'daji, jeji', 'noun', 'nature', 'beginner'),
('dùwò', 'grave', 'kabari', 'noun', 'places', 'advanced'),
('dìmlìm', 'charcoal, soot', 'gawayi, kunkunniya', 'noun', 'materials', 'intermediate'),
('dùwàaɣnò', 'groundnut', 'gyaɗa', 'noun', 'food', 'beginner'),
('dìŋ1', 'laterite', 'marmara', 'noun', 'materials', 'advanced'),
('dùyó', 'fly', 'ƙuda', 'noun', 'animals', 'beginner'),
('dìŋ2', 'black', 'baƙi', 'adjective', 'colors', 'beginner')

ON CONFLICT (goji_word) DO NOTHING;