-- Insert additional Goji vocabulary entries (batch 4)
INSERT INTO dictionary_entries (goji_word, english_translation, hausa_translation, part_of_speech, difficulty_level) VALUES
('sháafì', 'religious object', 'abin addini', 'noun', 'intermediate'),
('shìlím', 'mongoose', 'tunku', 'noun', 'beginner'),
('shèewò', 'plant, transplant', 'shuka', 'verb', 'beginner'),
('shìm', 'drum (hour glass)', 'kalangu', 'noun', 'intermediate'),
('shábá', 'lie', 'karya', 'noun', 'beginner'),
('shìm', 'cough', 'tari', 'noun', 'beginner'),
('shàɣlò', 'sleep', 'barci', 'noun', 'beginner'),
('shìrìm', 'fish', 'kifi', 'noun', 'beginner'),
('shàmmàm', 'viper', 'See: kúrét; rêw', 'noun', 'intermediate'),
('shìrìp', 'woman', 'mace', 'noun', 'beginner'),
('shàŋà', 'bridegroom', 'ango', 'noun', 'intermediate'),
('shíwó', 'small ant', 'kiyashi', 'noun', 'beginner'),
('shànɣò', 'exchange goods', 'kaya', 'verb', 'intermediate'),
('shìwòn', 'shrew', 'jaɓa', 'noun', 'beginner'),
('shányè', 'yam(s)', 'doya', 'noun', 'beginner'),
('shìwrì', 'long-tail rat', 'ɓera, kusu. See: àllágà', 'noun', 'beginner'),
('sháppàn', 'diarrhoea', 'zawo', 'noun', 'intermediate'),
('shíyá', 'menstruation', 'haila', 'noun', 'intermediate'),
('shàrgey', 'weapon', 'makami', 'noun', 'intermediate'),
('shò', 'leg, foot', 'ƙafa', 'noun', 'beginner'),
('shárí', 'load', 'kaya', 'noun', 'beginner'),
('shɔ̀', 'drink', 'sha', 'verb', 'beginner'),
('shàw', 'Guinea corn', 'dawa', 'noun', 'beginner'),
('shɔ́k', 'hair', 'gashi', 'noun', 'beginner'),
('sháwán', 'spirit', 'iska', 'noun', 'intermediate'),
('shɔ́k fɔ̀k', 'beard', 'gemu', 'noun', 'beginner'),
('shə̀əd', 'morning', 'safiya', 'noun', 'beginner'),
('shɔ́k shìk', 'body hair', 'gashin jiki', 'noun', 'beginner'),
('shégní', 'bee', '', 'noun', 'beginner'),
('shɔ̀kh', 'hair, fur, feather', 'gashi', 'noun', 'beginner'),
('shɔ̀mmɔ̀', 'name', 'suna', 'noun', 'beginner'),
('shègré', 'the past', 'da', 'noun', 'intermediate'),
('shɔ̀r', 'dance', 'rawa', 'noun', 'beginner'),
('shégrí', 'hiccough', 'shaƙuwa', 'noun', 'beginner'),
('shóorím', 'root', 'saiwa', 'noun', 'beginner'),
('shékì', 'between', 'tsakanin', 'preposition', 'intermediate'),
('shù', 'eat (tuwo)', 'ci (tuwo)', 'verb', 'beginner'),
('shèllè', 'vulture', 'ungulu', 'noun', 'beginner'),
('shúná', 'dream', 'mafarki', 'noun', 'beginner'),
('shèmù', 'poison', 'guba', 'noun', 'intermediate'),
('shúŋúr', 'shinbone', 'sangali', 'noun', 'intermediate'),
('shén', 'cleverness', 'azanci, fasaha', 'noun', 'intermediate'),
('shúrɔ́', 'laugh', 'dariya', 'noun', 'beginner'),
('shènè', 'year', 'shekara', 'noun', 'beginner'),
('shúrùk', 'river', 'kogi', 'noun', 'beginner'),
('shéwó', 'fear, shame', 'tsoro, kunya', 'noun', 'beginner'),
('shùjì', 'male', 'miji', 'noun', 'beginner'),
('shí mínná', 'wall (house)', 'bango', 'noun', 'beginner'),
('shùkkàn kírá', 'fist', 'dunƙulen hannu', 'noun', 'intermediate'),
('shìɓɔ̀ gə̀də̀', 'terrace', 'gandu', 'noun', 'intermediate'),
('shùnò', 'skin', 'feɗe', 'verb', 'beginner'),
('shìɗə̀r', 'fat', 'fet', 'noun', 'beginner'),
('shùngù', 'cloud', 'gajimare, girgije', 'noun', 'beginner'),
('shíɣá', 'loss', 'rashi', 'noun', 'intermediate'),
('shúurò shàw', 'threshing', '', 'noun', 'intermediate'),
('shìilà', 'stone, rock, hill', 'dutse', 'noun', 'beginner'),
('shùrmì', 'hare', 'zomo', 'noun', 'beginner'),
('shìilà ɓàalà', 'escarpment', 'dutse', 'noun', 'intermediate'),
('shùurò', 'fry', 'soya, toya', 'verb', 'beginner'),
('shíiwé', 'firewood', 'itace', 'noun', 'beginner'),
('shùuɣò', 'cheat', 'cuta', 'verb', 'intermediate'),
('shìk', 'hundred', 'ɗari', 'number', 'intermediate'),
('shùwè', 'wood', 'itace', 'noun', 'beginner'),
('shwè', 'bush', 'daji, jeji', 'noun', 'beginner'),
('shwìyàk', 'sand', 'yashi', 'noun', 'beginner'),
('shwíyə̀k', 'dew', 'raɓa', 'noun', 'beginner'),
('shìk', 'body', 'jiki', 'noun', 'beginner'),
('ríwít', 'fire-place', 'wurin wuta', 'noun', 'beginner'),
('rè', 'enter', 'shiga', 'verb', 'beginner'),
('ròmìsh', 'twin', 'ɗan tagwai', 'noun', 'beginner');