-- Insert additional Goji vocabulary entries (batch 6 - letters W and Y)
INSERT INTO dictionary_entries (goji_word, english_translation, hausa_translation, part_of_speech, difficulty_level) VALUES
('wànɣì', 'trousers', 'wando', 'noun', 'beginner'),
('wìyàk', 'bone', 'ƙashi', 'noun', 'beginner'),
('wàré', 'mouse', 'ɓera', 'noun', 'beginner'),
('wɔ̀jɔ̀', 'avoid, abstain', 'ƙarauce wa', 'verb', 'intermediate'),
('wàrù', 'come', 'zo', 'verb', 'beginner'),
('wɔ̀kù', 'helmet', 'hular kwano', 'noun', 'intermediate'),
('wàw', 'sacrifice', 'hadaya', 'noun', 'intermediate'),
('wɔ̀kù', 'cap', 'hula', 'noun', 'beginner'),
('wè bì gùrùŋ', 'saddle', 'sirdi', 'noun', 'intermediate'),
('wúró', 'tooth', 'haƙori', 'noun', 'beginner'),
('wè fɔ́ gùrùŋ', 'bit (horse)', 'linzami', 'noun', 'intermediate'),
('wùjìn', 'nose', 'hanci', 'noun', 'beginner'),
('wè kírá', 'bracelet', 'abin hannu', 'noun', 'intermediate'),
('wùlù', 'strike fire', 'kunna wuta', 'verb', 'intermediate'),
('wè kúmó', 'earring', 'yan kunne', 'noun', 'intermediate'),
('wùllò', 'bubble, ferment', 'ruɓa', 'verb', 'intermediate'),
('wè túr', 'necklace', 'abin wuya', 'noun', 'intermediate'),
('wùrì', 'breast', 'nono', 'noun', 'beginner'),
('wə̀rì', 'breast', 'nono', 'noun', 'beginner'),
('wùrìn', 'medicine', 'magani', 'noun', 'beginner'),
('wìirì', 'Indian tamarind', 'tsamiya', 'noun', 'intermediate'),
('wùrɔ̀k', 'pus', 'mugunya', 'noun', 'intermediate'),
('wìshɔ̀', 'roast', 'gasa', 'verb', 'beginner'),
('yù mə̀n', 'brew (beer)', 'dafa', 'verb', 'intermediate'),
('yípó', 'evening, night, darkness', 'dare, duhu', 'noun', 'beginner'),
('yù mèrà', 'travel', 'yi tafiya', 'verb', 'beginner'),
('yìipò shìrìim', 'to fish', 'sunta, yi fatsa', 'verb', 'intermediate'),
('yàamúɣì', 'brother-in-law', 'ƙane, wa', 'noun', 'intermediate'),
('yò', 'call', 'kira', 'verb', 'beginner'),
('yàllò', 'shouting', 'ihu', 'noun', 'intermediate'),
('yù', 'do, make', 'yi', 'verb', 'beginner'),
('yàmmà', 'god', 'Allah, Ubangiji', 'noun', 'intermediate'),
('yù ɓèrà', 'cut marks', 'shasshauta', 'verb', 'intermediate'),
('yàrà shwè', 'hunt', 'farauta', 'noun', 'intermediate'),
('yù ɗìyò', 'marry', 'yi aure', 'verb', 'intermediate'),
('yèrà', 'itch', 'ƙaiƙayi', 'noun', 'intermediate'),
('yù gùp', 'rule', 'yi mulki', 'verb', 'intermediate'),
('yèrì', 'red ant', 'jan kiyashi', 'noun', 'beginner'),
('yù jírí', 'steal', 'sata', 'verb', 'intermediate'),
('yèrò', 'bite', 'ciza', 'verb', 'beginner'),
('yù nèy', 'fight', 'yi faɗa', 'verb', 'intermediate'),
('yìbà dèet', 'flame', 'harshen wuta', 'noun', 'intermediate'),
('yù shìlìp', 'suffer', 'sha wahala', 'verb', 'intermediate'),
('yìirà', 'reception', 'liyafa', 'noun', 'intermediate'),
('yùɣlà', 'medium size calabash', 'ƙwarya', 'noun', 'intermediate');