-- Insert additional Goji vocabulary entries (batch 5 - letters T, U, V)
INSERT INTO dictionary_entries (goji_word, english_translation, hausa_translation, part_of_speech, difficulty_level) VALUES
('tà', 'in, at, inside', 'a, ciki(n)', 'preposition', 'beginner'),
('tà ʔáà', 'stomach', 'ciki', 'noun', 'beginner'),
('tà ɓə̀ək', 'armpit', 'hamata', 'noun', 'beginner'),
('tàɓùk', 'land', 'ƙasa', 'noun', 'beginner'),
('tà gə̀də̀', 'slope', 'gangara', 'noun', 'intermediate'),
('tà gùmè', 'entrance hut', 'zaure', 'noun', 'intermediate'),
('tà kɔ̀nn', 'legal case', 'ƙara', 'noun', 'intermediate'),
('tà mínná(mù)', 'lineage', 'inside (our) house', 'noun', 'intermediate'),
('tà mínná(nò) tà múu', 'family', 'inside (my) house', 'noun', 'intermediate'),
('tà shúrùk', 'valley', 'kwari', 'noun', 'beginner'),
('tàa', 'shoe', 'takalma', 'noun', 'beginner'),
('tàará', 'unfarmed ground', 'in left place', 'noun', 'intermediate'),
('tàat', 'three', 'uku', 'number', 'beginner'),
('tàawa', 'tobacco', 'taba', 'noun', 'intermediate'),
('tálí', 'far', 'nesa', 'adverb', 'beginner'),
('tàŋgà', 'bull', 'là tàŋgà calf', 'noun', 'beginner'),
('tàvrò', 'west', 'yamma', 'noun', 'intermediate'),
('téelè', 'worm', 'tsutsa', 'noun', 'beginner'),
('télàŋ', 'cooking pot', 'tukunya', 'noun', 'beginner'),
('tèmèl', 'shoulder', 'kafaɗa', 'noun', 'beginner'),
('à tálím', 'not far', 'ba nesa ba', 'phrase', 'intermediate'),
('témmè1', 'right', 'dama', 'adverb', 'beginner'),
('témmè2', 'sweep, clean', 'share', 'verb', 'beginner'),
('téré', 'moon', 'wata', 'noun', 'beginner'),
('tèrèt', 'broom', 'tsintsiya', 'noun', 'beginner'),
('tìtɔ́ŋ', 'where', 'ina', 'adverb', 'beginner'),
('tòbbò', 'sow (seeds in holes)', 'shuka, yi binne', 'verb', 'intermediate'),
('tɔ̀ɗókù', 'fever', 'zazzaɓi', 'noun', 'beginner'),
('tɔ̀k', 'mat', 'tabarma', 'noun', 'beginner'),
('tɔ̀lɔ́tɔ̀lɔ', 'turkey', 'talotalo', 'noun', 'beginner'),
('tònnò', 'spin (thread), weave', 'kaɗa, saƙa', 'verb', 'intermediate'),
('tɔ̀ɔ', 'Talha gum Arabic tree', 'ƙaro', 'noun', 'intermediate'),
('árát tɔ̀ɔm', 'in front (of)', 'a gaba(n)', 'preposition', 'intermediate'),
('tùɓɓò', 'rubbish heap', 'juji', 'noun', 'beginner'),
('túɣá shìgnì', 'unnatural death', '', 'noun', 'advanced'),
('tùkkò', 'kill', 'kashe', 'verb', 'intermediate'),
('túmmò', 'guinea-fowl', 'zabo', 'noun', 'beginner'),
('twàanà', 'silk cotton tree (red flowers)', 'rimi', 'noun', 'intermediate'),
('twɔ̀ŋé', 'small calabash', 'ƙaramin duma', 'noun', 'beginner'),
('téré pé', 'white moon', 'farin wata', 'noun', 'intermediate'),
('ʔùn', 'pregnancy', 'ciki', 'noun', 'intermediate'),
('ùn', 'pregnancy', 'ciki', 'noun', 'intermediate'),
('vànà', 'black sesame', 'baƙin riɗi', 'noun', 'intermediate'),
('vìyè', 'sauce, soup', 'miya', 'noun', 'beginner'),
('vàré', 'he-goat', 'bunsuru', 'noun', 'beginner'),
('vònàk', 'song', 'waƙa', 'noun', 'beginner'),
('vèe', 'chin', 'haɓa', 'noun', 'beginner'),
('vɔ̀ɔn', 'pumpkin', 'kabewa', 'noun', 'beginner'),
('vìɣè', 'cobra', 'gamsheƙa', 'noun', 'intermediate'),
('vìɣè ʔèlèt', 'spitting cobra', '', 'noun', 'intermediate'),
('vùlùk', 'cave', 'kogon dutse', 'noun', 'intermediate'),
('vìnò', 'throw a stone', 'jefa dutse', 'verb', 'intermediate'),
('vúró', 'gun powder', 'albarushi', 'noun', 'intermediate'),
('vìn', 'grinding stone', 'dutsen niƙa', 'noun', 'intermediate'),
('vùrɔ̀', 'ashes', 'toka', 'noun', 'beginner'),
('vìyò1', 'demon, spirit', 'iska, aljani', 'noun', 'intermediate'),
('vùrùm', 'knee', 'gwiwa', 'noun', 'beginner'),
('vìyò2', 'rainy season', 'damina', 'noun', 'intermediate');