-- Add batch 2 of Goji dictionary entries (71 words) with NULL contribution_id for system imports
INSERT INTO dictionary_entries (
  goji_word, 
  english_translation, 
  hausa_translation, 
  part_of_speech, 
  semantic_category, 
  difficulty_level,
  contributor_id,
  contribution_id,
  approved_at,
  created_at
) VALUES 
-- B words
('bèe', 'shoot', 'harba', 'verb', 'actions', 'intermediate', gen_random_uuid(), NULL, now(), now()),
('bànà', 'antelope', 'mazo, ragon ruwa, gwanki', 'noun', 'animals', 'beginner', gen_random_uuid(), NULL, now(), now()),
('bàrà', 'trap', 'tarko', 'noun', 'tools', 'intermediate', gen_random_uuid(), NULL, now(), now()),
('bèndè', 'penis sheath', 'gidan azzakari', 'noun', 'body', 'advanced', gen_random_uuid(), NULL, now(), now()),
('bì', 'back, behind', 'baya', 'noun/prep', 'body/position', 'beginner', gen_random_uuid(), NULL, now(), now()),
('bì bìró', 'bark of tree', 'ɓawo', 'noun', 'nature', 'intermediate', gen_random_uuid(), NULL, now(), now()),
('bì gbɔ́ŋ', 'nape (of neck)', 'ƙeya', 'noun', 'body', 'intermediate', gen_random_uuid(), NULL, now(), now()),
('bì shò', 'footprint', 'sawun ƙafa', 'noun', 'body', 'intermediate', gen_random_uuid(), NULL, now(), now()),
('bìirìm', 'heel', 'diddige', 'noun', 'body', 'beginner', gen_random_uuid(), NULL, now(), now()),
('bìlìr', 'flower', 'fure', 'noun', 'nature', 'beginner', gen_random_uuid(), NULL, now(), now()),
('bìlìt', 'flower (variant)', 'fure', 'noun', 'nature', 'beginner', gen_random_uuid(), NULL, now(), now()),
('bìndìgà', 'gun', 'bindiga', 'noun', 'tools', 'intermediate', gen_random_uuid(), NULL, now(), now()),
('bìnnò', 'guest, stranger', 'baƙo', 'noun', 'social', 'beginner', gen_random_uuid(), NULL, now(), now()),
('bìró', 'tree with no leaves', 'itace', 'noun', 'nature', 'beginner', gen_random_uuid(), NULL, now(), now()),
('bùkwátì', 'bucket', 'bokiti', 'noun', 'tools', 'beginner', gen_random_uuid(), NULL, now(), now()),

-- ɓ words
('ɓàakh', 'wing', 'fiffike', 'noun', 'animals', 'beginner', gen_random_uuid(), NULL, now(), now()),
('ɓàkà', 'natron', '', 'noun', 'materials', 'advanced', gen_random_uuid(), NULL, now(), now()),
('ɓálá', 'tiredness', 'gajiya', 'noun', 'feelings', 'beginner', gen_random_uuid(), NULL, now(), now()),
('ɓáŋ', 'strength', 'ƙarfi', 'noun', 'qualities', 'beginner', gen_random_uuid(), NULL, now(), now()),
('ɓán fɔ̀k', 'courage', 'jaruntaka', 'noun', 'qualities', 'intermediate', gen_random_uuid(), NULL, now(), now()),
('ɓánnì', 'baobab tree', 'kuka', 'noun', 'nature', 'intermediate', gen_random_uuid(), NULL, now(), now()),
('ɓày', 'dog', 'kare', 'noun', 'animals', 'beginner', gen_random_uuid(), NULL, now(), now()),
('ɓə̀ək', 'wing(s)', 'fiffike', 'noun', 'animals', 'beginner', gen_random_uuid(), NULL, now(), now()),
('ɓèrà', 'facial markings', 'sasshawa', 'noun', 'culture', 'intermediate', gen_random_uuid(), NULL, now(), now()),
('ɓìrò', 'beat', 'buga', 'verb', 'actions', 'beginner', gen_random_uuid(), NULL, now(), now()),
('ɓìr(ì) shàw', 'flail', '', 'noun', 'tools', 'advanced', gen_random_uuid(), NULL, now(), now()),
('ɓòŋ bìró', 'trunk', 'gangar jiki', 'noun', 'nature', 'intermediate', gen_random_uuid(), NULL, now(), now()),
('ɓɔ̀ɔlì', 'east', 'gabas', 'noun', 'directions', 'beginner', gen_random_uuid(), NULL, now(), now()),
('ɓɔ̀rɔ̀n', 'type of millet', 'irin gero', 'noun', 'food', 'intermediate', gen_random_uuid(), NULL, now(), now()),
('ɓùk', 'soil', 'ƙasa', 'noun', 'nature', 'beginner', gen_random_uuid(), NULL, now(), now()),
('ɓwàarò ɗìyò', 'divorce', 'saki', 'noun', 'social', 'advanced', gen_random_uuid(), NULL, now(), now()),
('ɓwáré', 'rattle', 'caki', 'noun', 'tools', 'intermediate', gen_random_uuid(), NULL, now(), now()),
('ɓwèyù', 'underworld', '', 'noun', 'spiritual', 'advanced', gen_random_uuid(), NULL, now(), now()),
('ɓwòy', 'today', 'yau', 'adverb', 'time', 'beginner', gen_random_uuid(), NULL, now(), now()),

-- D words  
('dàbáŋ', 'festival', 'biki', 'noun', 'culture', 'beginner', gen_random_uuid(), NULL, now(), now()),
('dìnyì', 'sheep', 'tunkiya', 'noun', 'animals', 'beginner', gen_random_uuid(), NULL, now(), now()),
('nùn dìnyì', 'ewe', 'tunkiya', 'noun', 'animals', 'intermediate', gen_random_uuid(), NULL, now(), now()),
('dàmàl', 'bushy tail', 'gafiya', 'noun', 'animals', 'intermediate', gen_random_uuid(), NULL, now(), now()),
('dìráŋ', 'locust-bean tree', 'ɗorawa', 'noun', 'nature', 'intermediate', gen_random_uuid(), NULL, now(), now()),
('dáŋ', 'door', 'ɗaki', 'noun', 'household', 'beginner', gen_random_uuid(), NULL, now(), now()),
('dìishò', 'stamp, pound', 'daka', 'verb', 'actions', 'intermediate', gen_random_uuid(), NULL, now(), now()),
('dàŋ1', 'south', 'kuda', 'noun', 'directions', 'beginner', gen_random_uuid(), NULL, now(), now()),
('dòɣbɔ́', 'ruin', 'kango', 'noun', 'places', 'intermediate', gen_random_uuid(), NULL, now(), now()),
('dàŋ2', 'above', 'kan, bisa da', 'preposition', 'position', 'beginner', gen_random_uuid(), NULL, now(), now()),
('dòlòní', 'ant', 'kiyashi, cinnaka, tuma-da-gayya', 'noun', 'animals', 'beginner', gen_random_uuid(), NULL, now(), now()),
('dànàm', 'sister-in-law', 'ƙanwa', 'noun', 'family', 'intermediate', gen_random_uuid(), NULL, now(), now()),
('dòo', 'water', 'ruwa', 'noun', 'nature', 'beginner', gen_random_uuid(), NULL, now(), now()),
('dàngà', 'fence', 'shinge', 'noun', 'household', 'beginner', gen_random_uuid(), NULL, now(), now()),
('dòo wùrì', 'milk', 'nono', 'noun', 'food', 'beginner', gen_random_uuid(), NULL, now(), now()),
('dànyùkh', 'frog, toad', 'kwaɗo', 'noun', 'animals', 'beginner', gen_random_uuid(), NULL, now(), now()),
('dòodó', 'spirit', 'kurwa, aljani, iska', 'noun', 'spiritual', 'advanced', gen_random_uuid(), NULL, now(), now()),
('dàràŋ', 'sun', 'rana', 'noun', 'nature', 'beginner', gen_random_uuid(), NULL, now(), now()),
('dɔ̀ŋ', 'field, farm', 'gona', 'noun', 'places', 'beginner', gen_random_uuid(), NULL, now(), now()),
('dàràŋ dén', 'sunshine', 'hasken rana', 'noun', 'nature', 'beginner', gen_random_uuid(), NULL, now(), now()),
('dùbù', 'thousand', 'dubu', 'numeral', 'numbers', 'intermediate', gen_random_uuid(), NULL, now(), now()),
('də̀ɓɓà', 'hyena', 'kura', 'noun', 'animals', 'intermediate', gen_random_uuid(), NULL, now(), now()),
('dèet', 'fire', 'wuta', 'noun', 'nature', 'beginner', gen_random_uuid(), NULL, now(), now()),
('dùŋò', 'smoke', 'hayaƙi', 'noun', 'nature', 'beginner', gen_random_uuid(), NULL, now(), now()),
('dèwè', 'stick used to decorate pots', '', 'noun', 'tools', 'advanced', gen_random_uuid(), NULL, now(), now()),
('dúmmò', 'hoe', 'fartanya, hauya', 'noun', 'tools', 'beginner', gen_random_uuid(), NULL, now(), now()),
('dèy', 'sinew', 'agara', 'noun', 'body', 'advanced', gen_random_uuid(), NULL, now(), now()),
('dùurò', 'bambara nut', 'gujiya', 'noun', 'food', 'intermediate', gen_random_uuid(), NULL, now(), now()),
('dìgré', 'big storage pot', 'kwatarniya', 'noun', 'household', 'intermediate', gen_random_uuid(), NULL, now(), now()),
('dùwò', 'ghost', 'fatalwa', 'noun', 'spiritual', 'advanced', gen_random_uuid(), NULL, now(), now()),
('dìl bìró', 'forest', 'daji, jeji', 'noun', 'nature', 'beginner', gen_random_uuid(), NULL, now(), now()),
('dùwò', 'grave', 'kabari', 'noun', 'places', 'advanced', gen_random_uuid(), NULL, now(), now()),
('dìmlìm', 'charcoal, soot', 'gawayi, kunkunniya', 'noun', 'materials', 'intermediate', gen_random_uuid(), NULL, now(), now()),
('dùwàaɣnò', 'groundnut', 'gyaɗa', 'noun', 'food', 'beginner', gen_random_uuid(), NULL, now(), now()),
('dìŋ1', 'laterite', 'marmara', 'noun', 'materials', 'advanced', gen_random_uuid(), NULL, now(), now()),
('dùyó', 'fly', 'ƙuda', 'noun', 'animals', 'beginner', gen_random_uuid(), NULL, now(), now()),
('dìŋ2', 'black', 'baƙi', 'adjective', 'colors', 'beginner', gen_random_uuid(), NULL, now(), now());